### ISSUE TITLE
[win32] Issue for v0.12.2

### ISSUE THREAD

**Issue by ruerob** [itchio/itch#354] opened 2016-01-10 04:56 UTC
I can't start the itch.io app. There comes this error log:

Es gab ein Problem beim Einrichten: Error: spawn file ENOENT
    at exports._errnoException (util.js:856:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:465:9)
    at process._tickCallback (node.js:379:17)

Have I done something wrong?

Edit:
I'm on win 10 64bit. An older version of the app was running smoothly here: i think it was something with 0.11.x.
I've first installed the new version without deinstalling the old one. There came an error when I tried to start the app. After that I deinstalled and reinstalled the app, but the error is still there.

**Comment by fasterthanlime** [comment] 2016-01-10 05:12
nope, my bad. dupe of #353 though, v0.12.3 is coming

**Closed as completed by fasterthanlime** 2016-01-10 05:12 UTC

**Comment by ruerob** [comment] 2016-01-10 05:14
Thank you! :0)

**Comment by fasterthanlime** [comment] 2016-01-10 05:59
@ruerob 0.12.3 is out, should fix it
