### ISSUE TITLE
"Launch Game" and "Join Game" links for Multiplayer

### ISSUE THREAD

**Issue by aaronfranke** [itchio/itch#1726] opened 2018-03-03 07:01 UTC
Itch may not want to be a social platform, but I would still like it if Itch provided an easy way to join multiplayer games. Friends could send each other "join links" via services like Discord, which would open the game and join the server. Or, they could just send links to launch the game, then join in-game.

The Itch app already provides `itchio://games/144693` to open the game page. 

What if you could have links like: 

`itchio://games/144693/launch` (launch if installed, else open game page) or 

`itchio://games/144693/join/12.34.56.78:12345` (connect if open, launch and connect if installed but not open, else open game page)? 

Games could accept signals or launch arguments to join games, and have buttons in-game for creating join links, if they choose to implement the API in any or all of these ways.

The launch link would work regardless of a developer's support for the Itch app.

Related: https://github.com/itchio/itch.io/issues/536

**Comment by fasterthanlime** [comment] 2018-09-13 15:57
I'm interested in the "join" idea, but I think this should be tackled as part of a bigger "online services" update to itch.io + the app.

The problem with URLs like `itch://games/;game_id` is that a single game may have multiple uploads. Upload IDs vary across platform, so having an `itch://games/:game_id?upload_id=456` URL isn't a solution either.

What I think we need for this is "products", ie:

  * A developer has multiple
    * ...pages, which can have multiple
      * ...products, each of which can have multiple
         * ...uploads (to support different platforms)

Then URLs could be stable (with the product ID).

I'm not sure when that'll happen though, so I'd rather close this for the time being - it's good that the issue is here for future reference, but it's not something I can fix in a few commits.

**Closed as completed by fasterthanlime** 2018-09-13 15:57 UTC
