### ISSUE TITLE
[maybe] Mac setup progress bar didn't animate

### ISSUE THREAD

**Issue by OneSadCookie** [itchio/itch#2093] opened 2018-09-07 11:23 UTC
itch: kitch 24.63.0
macOS: Mojave 10.14 Beta (18A377a)

I'm not certain of this one, but I think the progress bar in the setup window didn't animate as the installation occurred.

It's possible I'm blind, or that it doesn't animate when the setup app is backgrounded, or that it did animate but went by faster than I was paying attention. Don't put too much weight on this report if you can't reproduce it!

**Comment by fasterthanlime** [comment] 2018-09-10 12:34
> Don't put too much weight on this report if you can't reproduce it!

Tried on 5 machines, couldn't reproduce it. It is _pretty fast_ if itch is already installed. Closing for now!

**Closed as completed by fasterthanlime** 2018-09-10 12:34 UTC
