### ISSUE TITLE
Clicking a filter will also click behind it

### ISSUE THREAD

**Issue by Deozaan** [itchio/itch#1232] opened 2017-05-26 04:06 UTC
In the Library tab of Itch, if I click the down arrow at the top center to select a filter (Compatible, Installed, Owned) and then click on a filter, the click will select the filter but also click through to whatever element is behind it. So if there's a game behind the filter dropdown, selecting a filter will immediately open the game's page in a new tab.

![itch dropdown clickthrough bug](https://cloud.githubusercontent.com/assets/227734/26480313/3f72b7d0-4196-11e7-9e1f-b207c711157d.gif)

Itch 23.4.1 on Windows 10 Pro 1703 (15063.332)

**Comment by fasterthanlime** [comment] 2017-05-26 10:11
Actually, I noticed that too, and fixed it in the big-ass-refactoring branch that's been pending ever since v23.4.0 :)

(In the meantime I suggest navigating with arrow keys + pressing enter. If there's another critical bug I'll probably tack a fix to that with the same release, otherwise I'll just try to get big-ass-refactoring shipped as soon as I can).

**Comment by fasterthanlime** [comment] 2017-06-03 13:12
Confirmed that this is no longer a thing in v25, closing.

**Closed as completed by fasterthanlime** 2017-06-03 13:12 UTC
