### ISSUE TITLE
Run JAR files

### ISSUE THREAD

**Issue by solarflux** [itchio/itch#243] opened 2015-12-23 01:42 UTC
Out of the box JAR support would be nice for games like Kyro (http://solarlune.itch.io/kyro) that are distributed as JARs within ZIP archives

**Comment by fasterthanlime** [comment] 2015-12-23 09:41
This is planned but also a duplicate of an existing issue :)

**Comment by smiley** [comment] 2016-01-01 18:51
If support is added, a JRE should never be installed by the client. It should auto-detect one on the user's PC or suggest installation (with a direct link to Oracle's website) if it can't be found.

**Comment by fasterthanlime** [comment] 2016-01-13 12:21
(#134 is a sister issue of this, discussion is split between them unfortunately so not closing either)

**Comment by fasterthanlime** [comment] 2016-05-07 00:26
We do that now! Although we don't detect or complain about a JRE, we just try to run the thing.

**Closed as completed by fasterthanlime** 2016-05-07 00:26 UTC
Labels: compatibility
