### ISSUE TITLE
Games do not show up in Launchpad on Mac, they can only be launched from itch itself.

### ISSUE THREAD

**Issue by quenz** [itchio/itch#1585] opened 2017-12-26 08:07 UTC
Launchpad is a little icon on the dock on Mac. When you click it, all your apps show up. It's similar to Windows' start menu. But none of the itch apps show up in Launchpad. Not unless you navigate to the folder itch keeps its apps, then either copy them to the main Applications folder, or make aliases (shortcuts) to them.

**Comment by fasterthanlime** [comment] 2018-09-18 13:13
Duplicate of https://github.com/itchio/itch/issues/864

**Closed as completed by fasterthanlime** 2018-09-18 13:13 UTC
