### ISSUE TITLE
When purchasing through Itch app, you need to reenter your postal address (v0.11.3)

### ISSUE THREAD

**Issue by TerryCavanagh** [itchio/itch#265] opened 2015-12-29 14:46 UTC
Just tried to buy a game through the itch app, and when choosing paypal as a payment method, the app asks me to enter my postal address, even though I've already bought games through itch in the past.

(I'm posting all these issues as a sign of affection, btw, I think the app is amazing)

**Comment by leafo** [comment] 2015-12-29 21:36
Thanks for the issues, we appreciate it!

Just verifying, you have an addressed saved here: http://itch.io/user/settings/billing-address and it correctly fills the fields out when buying through your browser?

**Comment by TerryCavanagh** [comment] 2015-12-30 12:04
Huh! I do not have an address saved there, weird! I've definitely filled this in in the past, tho!

**Comment by TerryCavanagh** [comment] 2015-12-30 12:06
(Or, to be more accurate, I've filled in my address when buying games on itch in the past, but I haven't filled it in on that exact page and saved it in the past. Maybe this is intended behaviour, in which case fair enough, opps)

**Comment by fasterthanlime** [comment] 2015-12-31 09:10
> I've filled in my address when buying games on itch in the past

Off the top of my head, _when logged in_, it collects address and puts it in your profile, but when you're not (yet buying for your own e-mail address) I don't think it does.

**Comment by fasterthanlime** [comment] 2016-01-13 12:39
Looks like this isn't an itch issue then? If someone manages to reproduce this (having to re-enter postal address when purchasing on itch.io whereas they're pretty sure they did before), https://github.com/leafo/itch.io/issues is the right place to file a fresh issue.

Closing for now! :star2:

**Closed as completed by fasterthanlime** 2016-01-13 12:39 UTC
