### ISSUE TITLE
Doesn't have an app icon on Ubuntu

### ISSUE THREAD

**Issue by stuartlangridge** [itchio/itch#804] opened 2016-07-15 11:33 UTC
In the Ubuntu launcher, a running itch.io desktop client (downloaded as tar.xz) doesn't have an icon specified. (You should be able to specify this when creating a `BrowserWindow`.)

**Comment by fasterthanlime** [comment] 2016-07-15 11:35
Well, the code to do it is definitely there:

``` javascript
  const iconPath = `${__dirname}/../static/images/tray/${app.getName()}.png`

  const window = new BrowserWindow({
    title: app.getName(),
    icon: iconPath,
    width, height,
    center,
    show: false,
    autoHideMenuBar: true,
    backgroundColor: darkMineShaft,
    titleBarStyle: 'hidden'
  })
```

but perhaps the path can't be read from a production build, which is in an .asar archive. I wonder if I should be using `file://` instead.

**Comment by stuartlangridge** [comment] 2016-07-15 11:36
Yeah, I've just looked at the code myself and seen that. Not sure why that isn't working...

**Comment by stuartlangridge** [comment] 2016-07-15 11:37
I think https://github.com/electron/electron/issues/6205 might be relevant here!

**Comment by fasterthanlime** [comment] 2016-07-15 11:38
Interesting! Definitely used to that kind of bugs from Electron by now ;) there's already logic in `tray.js` to pick a small-enough icon.

**Comment by fasterthanlime** [comment] 2016-07-15 11:42
I wonder if I can install the Unity launcher on Debian without breaking anything (I have an Ubuntu VM somewhere, but do most of my testing on Debian).

**Comment by stuartlangridge** [comment] 2016-07-15 11:43
Honestly, you're almost certainly better off firing up an Ubuntu VM. Unity is a bit tied to Ubuntu...

**Comment by fasterthanlime** [comment] 2016-07-16 09:03
Applied the fix linked to in 6205, pushed a new [canary build](https://github.com/itchio/kitch) to test it, will be up soon.

**Comment by fasterthanlime** [comment] 2016-07-16 11:33
In my ubuntu 16.04 VM, it looks like both itch 18.3.0 (latest stable) and 18.3.1-canary (beta/canary build I just pushed) have an icon in the Unity launcher when installed from .deb (with a proper .desktop file):

![no-install-locations](https://cloud.githubusercontent.com/assets/7998310/16894529/1e0fb144-4b59-11e6-8b90-7f69accf37be.png)

However, after uninstalling the .deb (important, otherwise it'll pick up the icon from `/usr/share/applications`), I can confirm that 18.3.0 lacked an icon, and that 18.3.1-canary has one:

![appicon-fix](https://cloud.githubusercontent.com/assets/7998310/16894549/e52bc38a-4b59-11e6-81ef-a95e7fa04ca7.png)

Closing as this'll ship in the next stable version.

**Closed as completed by fasterthanlime** 2016-07-16 11:33 UTC
