### ISSUE TITLE
[darwin] tool Tilemancer broken for v0.13.2

### ISSUE THREAD

**Issue by KaiClavier** [itchio/itch#547] opened 2016-04-07 18:44 UTC
:rotating_light: tool [Tilemancer](https://led.itch.io/tilemancer) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/f6ad442035a9c34ae72d052b0b3b4fd9).

:running: Uhh first time doing a bug report like this, hope this is right!

**Comment by fasterthanlime** [comment] 2016-04-07 18:47
Ah, looks like it's failing to parse the output of hdiutil. Will take a look after 0.14.x is out

**Comment by fasterthanlime** [comment] 2016-05-06 16:45
Definitely fixed in v17 / duplicate of a bunch of other issues

**Closed as completed by fasterthanlime** 2016-05-06 16:45 UTC
