### ISSUE TITLE
[linux] Broken game for v0.10.2

### ISSUE THREAD

**Issue by szabba** [itchio/itch#182] opened 2015-12-18 14:21 UTC
Game [AirC.A.T](http://tsfreddie.itch.io/aircat) is broken for me.

Here's the [debug log](https://gist.github.com/4e40c1b4efac50613851).

**Comment by fasterthanlime** [comment] 2015-12-19 14:02
Hey thanks for your report! :tada:

This is a duplicate of #169, so I'm closing this to track it there instead.

**Closed as completed by fasterthanlime** 2015-12-19 14:02 UTC
