### ISSUE TITLE
Unable to install itch client on Windows 10 

### ISSUE THREAD

**Issue by lmichaela94** [itchio/itch#2435] opened 2020-06-13 14:40 UTC
I attempted to install the itch client and received this error log:

> Something went wrong
> 
> itch-setup, v1.18.0, built on Apr 10 2019 @ 06:29:17, ref 57838bc373361f2c8938336674247f869999e862
> 
> Get https://w3g3a5v6.ssl.hwcdn.net/build/116009/437355-signature-default?GoogleAccessId=uploader@moonscript2.iam.gserviceaccount.com&Expires=1592058677&Signature=Ok3hQUo4qcJMPi7MyyB26c9ROsuLnT0KvNtheaYIa08k2yMMMQtMUMpNo%2FatXnAEpoNJtDtEPxwGRKOUErb2dkbKFzBSA7SFHDJ5wXxQq4Z13UrSOOhFeANPaQDu6TIgzZuAz3RM%2BVkEH1Iy0WLdQQkKPdpYlVj%2ByL7MQJWyqsFikrM0Mt%2BFXgY%2BFfaX7o0Sjj8DgHneqc8C3Bx0SD%2Fcefr2Mqz1qhJkUAkSrQR6dfnPRrtpyiJ4GvorU3wKgSEWQGIwlsxxgr%2BlP2e%2Fb%2F%2BHSUwD6I4frUPQCR5GP2poRYJmGmrzj6lDIC%2FGlrvX94Lh6pKdBe5hn4U9rwzh0bb2IQ==&hwexp=1592058967&hwsig=3f6902b236c9108faa4c1fe1a374367e: dial tcp: i/o timeout
> htfs connect
> htfs.Open (initial request)
> while opening remote signature file
> Error during warm-up

**Comment by aktentasche** [comment] 2020-06-15 20:52
Duplicate of #2389

**Comment by zapper83** [comment] 2020-06-16 01:43
Go to the folder you installed the app, default is C:\Users\USERNAME\AppData\Local\itch, delete it and try to install again. Worked for me.

**Comment by ClarkEagling** [comment] 2020-06-16 02:16
My fix: download the install zip manually at  https://broth.itch.ovh/itch/windows-amd64/25.4.0/archive/default 
put the unzipped contents in C:\Users\USERNAME\AppData\Local\itch\staging\ 
and run the itch app found there.

**Closed as completed** 2020-06-16 07:16 UTC
