### ISSUE TITLE
[win32] Crash report for v0.10.2

### ISSUE THREAD

**Issue by fritzy** [itchio/itch#171] opened 2015-12-17 19:36 UTC
Crash log:

```
Error: Cannot find module '../protocol'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.defineProperties.protocol.get [as protocol] (C:\Users\natha\AppData\Local\itch\app-0.10.2\resources\atom.asar\browser\api\lib\exports\electron.js:75:16)
    at EventEmitter.<anonymous> (C:\Users\natha\AppData\Local\itch\app-0.10.2\resources\atom.asar\browser\lib\chrome-extension.js:75:24)
    at EventEmitter.g (events.js:260:16)
    at emitOne (events.js:82:20)
    at EventEmitter.emit (events.js:169:7)
```

Went to help->check for update->click to restart and apply update

**Comment by fasterthanlime** [comment] 2015-12-17 19:40
I saw that once too, in different circumstances. Sounds like an error in electron itself.

**Comment by fritzy** [comment] 2015-12-17 19:42
Does it every time it starts now. I'll take a deeper look when I have time.
Doesn't actually close the window. Still shows click to restart.

**Comment by fasterthanlime** [comment] 2015-12-19 18:20
duplicate of #202

**Closed as completed by fasterthanlime** 2015-12-19 18:20 UTC
