### ISSUE TITLE
🍎 Testing games that require password v22.2.0

### ISSUE THREAD

**Issue by amidos2006** [itchio/itch#1084] opened 2016-12-21 14:23 UTC
Happened when I try to add a game in testing that requires password, after adding the password this happened :(

Event log:

```
API Error: invalid game

stack:
API Error: invalid game
    at ApiError (/Applications/itch.app/Contents/Resources/app.asar/appsrc/util/api.ts:331:5)
    at Client.<anonymous> (/Applications/itch.app/Contents/Resources/app.asar/appsrc/util/api.ts:87:13)
    at next (<anonymous>)
    at fulfilled (/Applications/itch.app/Contents/Resources/app.asar/app/util/api.js:12:58)
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

**Comment by fasterthanlime** [comment] 2016-12-21 14:24
Yeah that's a dupe of #1080 - funny we never ran into that before! I'll see what it takes in API changes to get that to work.

**Closed as completed** 2017-03-28 03:57 UTC
