### ISSUE TITLE
[win32] game BoltStorm broken for v0.11.3

### ISSUE THREAD

**Issue by ctstrope** [itchio/itch#256] opened 2015-12-26 22:00 UTC
:rotating_light: Game [BoltStorm](http://kualitygames.itch.io/boltstorm) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/9ea1d5d5d29e2df0a2de).

:running: Any additional details can go here!

**Comment by fasterthanlime** [comment] 2015-12-29 08:35
Hey @ctstrope, thanks for your report!

This seems to be a duplicate of #242 — the developer of BoltStorm should repack their games using .zip so that it works in the itch.io app.

**Closed as completed by fasterthanlime** 2015-12-29 08:35 UTC
