### ISSUE TITLE
[linux] game Pixel Dungeon broken for v0.13.2

### ISSUE THREAD

**Issue by peregrin-tux** [itchio/itch#567] opened 2016-04-19 04:41 UTC
:rotating_light: game [Pixel Dungeon](https://watabou.itch.io/pixel-dungeon) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/52cae7db6718d8c2b66954dc65cb845a).

:running: The game never start. :cry:

**Comment by fasterthanlime** [comment] 2016-04-19 09:20
Oh, it's a jar! Will work in v0.14.x, duplicate of #134

**Closed as completed by fasterthanlime** 2016-04-19 09:20 UTC
