### ISSUE TITLE
[win32] tool Duality broken for v0.13.2

### ISSUE THREAD

**Issue by JoseRivas1998** [itchio/itch#531] opened 2016-03-25 20:27 UTC
:rotating_light: tool [Duality](https://adamslair.itch.io/duality) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/dd9829705c6f80b792f3).

:running: Any additional details can go here!

**Comment by fasterthanlime** [comment] 2016-05-06 22:18
Dupe of #441, dev fixed it 12 days ago :)

**Closed as completed by fasterthanlime** 2016-05-06 22:18 UTC
