### ISSUE TITLE
Can't install the app. Get this error during installation

### ISSUE THREAD

**Issue by kdavidson925** [itchio/itch#2437] opened 2020-06-15 18:52 UTC
Something went wrong

itch-setup, v1.18.0, built on Apr 10 2019 @ 04:28:23, ref 57838bc373361f2c8938336674247f869999e862

Get https://broth.itch.ovh/itch/windows-amd64/25.4.0/archive/default?downloadSessionId=c711d7dc-f8d6-43bb-ae13-072208fb2807: unexpected EOF
htfs connect
github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr.(*ArchiveHealer).heal
	C:/Multi-Runner/builds/58469115/0/itchio/itch-setup/src/github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr/archive_healer.go:274
github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr.(*ArchiveHealer).Do.func3
	C:/Multi-Runner/builds/58469115/0/itchio/itch-setup/src/github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr/archive_healer.go:102
runtime.goexit
	C:/Go/src/runtime/asm_386.s:1321
github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr.(*ArchiveHealer).Do
	C:/Multi-Runner/builds/58469115/0/itchio/itch-setup/src/github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr/archive_healer.go:209
github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr.(*ValidatorContext).Validate.func5
	C:/Multi-Runner/builds/58469115/0/itchio/itch-setup/src/github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr/validator.go:138
runtime.goexit
	C:/Go/src/runtime/asm_386.s:1321
while installing
Error during warm-up

**Comment by benoleary** [comment] 2020-06-15 19:56
I also have the same problem (Windows 7 Enterprise, Service Pack 1, 64-bit).

**Comment by mr-islam** [comment] 2020-06-15 20:39
Same

**Comment by aktentasche** [comment] 2020-06-15 20:52
Duplicate of #2389

**Comment by zapper83** [comment] 2020-06-16 01:41
Go to the folder you installed the app, default is C:\Users\USERNAME\AppData\Local\itch, delete it and try to install again. Worked for me.

**Comment by ClarkEagling** [comment] 2020-06-16 02:15
My fix: download the install zip manually at  https://broth.itch.ovh/itch/windows-amd64/25.4.0/archive/default 
put the unzipped contents in C:\Users\USERNAME\AppData\Local\itch\staging\ 
and run the itch app found there.

**Closed as completed** 2020-06-16 07:16 UTC
