### ISSUE TITLE
[win32] game Succulent broken for v0.13.2

### ISSUE THREAD

**Issue by eltorga** [itchio/itch#499] opened 2016-03-03 18:02 UTC
:rotating_light: game [Succulent](https://radiatoryang.itch.io/succulent) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/7a7f41d05446beb2ab6f).

:running: Any additional details can go here!

**Comment by fasterthanlime** [comment] 2016-03-03 19:21
duplicate of #473

**Closed as completed by fasterthanlime** 2016-03-03 19:21 UTC
