### ISSUE TITLE
[win32] Crash report for v0.10.2

### ISSUE THREAD

**Issue by noidexe** [itchio/itch#190] opened 2015-12-18 23:30 UTC
After clicking on "Click to restart & apply update!"

Crash log:

```
Error: Cannot find module '../protocol'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.defineProperties.protocol.get [as protocol] (C:\Users\Noid\AppData\Local\itch\app-0.10.2\resources\atom.asar\browser\api\lib\exports\electron.js:75:16)
    at EventEmitter.<anonymous> (C:\Users\Noid\AppData\Local\itch\app-0.10.2\resources\atom.asar\browser\lib\chrome-extension.js:75:24)
    at EventEmitter.g (events.js:260:16)
    at emitOne (events.js:82:20)
    at EventEmitter.emit (events.js:169:7)
```

**Comment by fasterthanlime** [comment] 2015-12-18 23:41
@noidexe is there a file named `protocol.js` at this path? `C:\Users\Noid\AppData\Local\itch\app-0.10.2\resources\atom.asar\browser\api\lib\`

**Comment by noidexe** [comment] 2015-12-18 23:58
That path doesn't exist. <code>C:\Users\Noid\AppData\Local\itch\app-0.10.2\resources\atom.asar</code> is a file. 
It has a header <code>0400 0000 ec0a 0000 e80a 0000 e30a 0000</code>and the rest seems to be json and javascript. It mentions protocol.js once.

**Comment by noidexe** [comment] 2015-12-18 23:59
[atom.asar.zip](https://github.com/itchio/itch/files/67312/atom.asar.zip)

**Comment by fasterthanlime** [comment] 2015-12-19 00:42
ah, I'm dumb, of course it's an `.asar` archive — one can list its content / extract it with [this package](https://www.npmjs.com/package/asar)

I'll look into it more later, I know I've seen that once win32, and it's been reported at least 7 times, but it seems to be only when launching a second instance of the app — which should only focus the 1st instance and quit immediately anyway.

Thanks for packing your atom.asar up! I'll look into it more after getting some rest. :+1: :100: :tada:

**Comment by fasterthanlime** [comment] 2015-12-19 18:20
duplicate of #202

**Closed as completed by fasterthanlime** 2015-12-19 18:20 UTC
