### ISSUE TITLE
Ubuntu-based Software Center considers package to be of bad quality.

### ISSUE THREAD

**Issue by ppvk** [itchio/itch#93] opened 2015-12-14 19:47 UTC
Details:

Lintian check results for /home/username/Downloads/itch_0.8.1_amd64.deb:
E: itch: control-file-has-bad-permissions triggers 0664 != 0644
E: itch: maintainer-name-missing amos@itch.io
Use of uninitialized value $name in pattern match (m//) at /usr/share/perl5/Lintian/Check.pm line 203.

**Comment by fasterthanlime** [comment] 2015-12-14 19:47
Dupe of #84 but will leave open so people don't re-open it over and over

**Comment by fasterthanlime** [comment] 2015-12-14 20:02
> E: itch: control-file-has-bad-permissions triggers 0664 != 0644

any idea what this refers to? @jordansissel is that something fpm generates because I'm using `--after-install` ?

**Comment by fasterthanlime** [comment] 2015-12-14 20:02
> E: itch: maintainer-name-missing amos@itch.io

fixed in https://github.com/itchio/ci.itch.ovh/commit/aefbefe9ebfd0329f52f998ab2e420ffa6581288 — will be in next release

**Comment by fasterthanlime** [comment] 2015-12-14 20:02
> Use of uninitialized value $name in pattern match (m//) at /usr/share/perl5/Lintian/Check.pm line 203.

hoping this is related to maintainer-name

**Comment by fasterthanlime** [comment] 2015-12-14 22:24
> E: itch: control-file-has-bad-permissions triggers 0664 != 0644

still present in 0.9.1, will fix later...

**Comment by jordansissel** [comment] 2015-12-15 02:55
@fasterthanlime Hmm, weird. fpm uses lintian in its test suite. I wonder if this is a new error in lintian? I'll take a look soon. <3

**Comment by fasterthanlime** [comment] 2015-12-15 14:18
> E: itch: control-file-has-bad-permissions triggers 0664 != 0644

can confirm that this is the only remaining error in 0.9.3

**Comment by fasterthanlime** [comment] 2015-12-15 14:21
@jordansissel fpm doesn't chmod 'triggers', and possibly the default mode on our build nodes is `0664` ? https://github.com/jordansissel/fpm/blob/15b050e5991389f7aabc0e04f7c8c52e90242a7b/lib/fpm/package/deb.rb#L828

**Comment by fasterthanlime** [comment] 2015-12-15 14:26
@jordansissel can confirm, on Ubuntu Wily 12.04, with ruby 2.2 installed from repository packages, the following code:

``` ruby
File.open('triggers', 'a') do |f|
  f.write('Hello.')
end
```

...creates a file with `664` permissions rather than `644`

**Comment by fasterthanlime** [comment] 2015-12-15 14:32
PR submitted, will use our fork until it lands: https://rubygems.org/gems/fpm-itchio

**Closed as completed** 2015-12-15 14:40 UTC
