### ISSUE TITLE
🏁 Feedback v23.4.2

### ISSUE THREAD

**Issue by gniaox** [itchio/itch#1368] opened 2017-07-26 16:52 UTC
Event log:

```
Error: ENOSPC: no space left on device, write
    at Object.<anonymous> (C:\Users\Galli\AppData\Local\itch\app-23.4.2\resources\app.asar\appsrc\util\sf.ts:135:21)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\Galli\AppData\Local\itch\app-23.4.2\resources\app.asar\app\util\sf.js:4:58)
```

**Comment by fasterthanlime** [comment] 2017-07-26 17:20
You need to make some space on your disk :)

We're planning on improving the experience when that happens / before that happens, see #801 and #874 for example.

Duplicate of #874

**Closed as completed by fasterthanlime** 2017-07-26 17:20 UTC
