### ISSUE TITLE
Played X hours; Never played

### ISSUE THREAD

**Issue by leafo** [itchio/itch#1924] opened 2018-07-11 18:21 UTC
![](http://leafo.net/shotsnb/2018-07-11_11-20-49.png)

**Comment by fasterthanlime** [comment] 2018-07-11 21:41
Was that imported from a previous version of kitch?

**Comment by fasterthanlime** [comment] 2018-07-11 21:43
I agree that it's silly to show this, but if it's caused by inconsistent data I'm not sure how far we want to go to specifically avoid that.

Maybe just not showing anything instead of "Never played" would work for all cases.

**Comment by leafo** [comment] 2018-07-13 00:21
> Was that imported from a previous version of kitch?

Yup, if you're sure it won't happen for regular users then it's fine

**Comment by fasterthanlime** [comment] 2018-08-17 19:06
> Yup, if you're sure it won't happen for regular users then it's fine

I am, closing.

**Closed as completed by fasterthanlime** 2018-08-17 19:06 UTC
