### ISSUE TITLE
🏁 Issue v23.4.1

### ISSUE THREAD

**Issue by cfveliz** [itchio/itch#1251] opened 2017-06-04 20:29 UTC
Itch v23.4.1
OS Windows 10 Creators Update
In Library view, when you click one of the filters suchs as "Installed", it also clicks the game image under it, so it opens a new tab with the game page in it and redirects you to that new tab.

**Comment by fasterthanlime** [comment] 2017-06-05 16:31
Duplicate of #1232, it's already fixed in master and will be deployed in the next release.

In the meantime, I recommend navigating the filters with up/down arrows and picking one with "Enter". Not ideal but less annoying than having tabs switch out from under you :)

**Closed as completed by fasterthanlime** 2017-06-05 16:31 UTC
