### ISSUE TITLE
[darwin] game Shiroi broken for v0.11.3

### ISSUE THREAD

**Issue by Bradshaw** [itchio/itch#266] opened 2015-12-29 19:34 UTC
:rotating_light: Game [Shiroi](http://gaeel.itch.io/shiroi) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/fd89409363b44e0b44b2).

:running: Attempted to launch this game from a fresh OSX install (just got this laptop a few hours ago), maybe the problem is with the game, soooo...

**Comment by Bradshaw** [comment] 2015-12-29 19:40
Yep, looking like a "my bad", I must have fudged up the build for this game. Other games using the same Löve 0.9 + custom toolchain are running fine (BLAPP & Zweinflugger!), and logs seem to show there's no executable included...

**Comment by fasterthanlime** [comment] 2016-01-08 00:08
@Bradshaw were you able to confirm that the problem was in the build and not the app ?

**Comment by Bradshaw** [comment] 2016-01-08 06:30
Problem is that it isn't a build, it's a Löve file, with instructions to grab Löve 0.9
In fact, I've tagged all my .love files as Mac/Linux/Windows compatible. I didn't realise at the time that this information was going to be used to inform automated installs.

**Comment by fasterthanlime** [comment] 2016-01-08 11:25
Ah, I see, then it's a duplicate of #135 :) :+1:

**Closed as completed by fasterthanlime** 2016-01-08 11:25 UTC
