### ISSUE TITLE
version 18.6.3 is totally broken [closed]

### ISSUE THREAD

**Issue by lahtis** [itchio/itch#870] opened 2016-09-06 16:10 UTC
v18.6.3 64-bit version is totally broken. I cant use program in Ubuntu 16.04 lts.
![itch](https://cloud.githubusercontent.com/assets/1613549/18281455/90353f20-7465-11e6-9e41-ec38db5b4197.png)

my hardware spec: https://gist.github.com/lahtis/8935236

**Comment by fasterthanlime** [comment] 2016-09-06 16:17
Taking a look at it now, thanks!

**Comment by fasterthanlime** [comment] 2016-09-06 16:17
@lahtis did you install via the .deb or manually via the .tar.xz ?

**Comment by lahtis** [comment] 2016-09-06 16:20
im install a 64-bit deb-package via debi. When im reinstall package and install older 18.6.2 package. I have a same problem.?? i also notived xenial 64-bit reposity not found. 404 error.

**Comment by fasterthanlime** [comment] 2016-09-06 16:22
Just installed 18.6.3 64-bit on Debian using the .deb and it seems to work fine. I'll try to reproduce on Ubuntu 16.04

**Comment by lahtis** [comment] 2016-09-06 16:24
that strange trying start again and older version now working. Maybe im trying again in new version. How about 404 xenial reposity error?

**Comment by fasterthanlime** [comment] 2016-09-06 16:26
> How about 404 xenial reposity error?

Can you give more details about this?

**Comment by lahtis** [comment] 2016-09-06 16:29
Now newest itch program working. And reposity also working no 404 errors. I think it was one glitch.

**Comment by fasterthanlime** [comment] 2016-09-06 16:30
Alright, thanks for reporting back. We've been rate limited by bintray today because we reached our storage quota, so this might've had something to do with it. Closing!

**Comment by lahtis** [comment] 2016-09-06 16:31
ok

**Closed as completed by fasterthanlime** 2016-09-06 16:30 UTC
