### ISSUE TITLE
[darwin] game Rogue's Eye broken for v0.13.2

### ISSUE THREAD

**Issue by servel333** [itchio/itch#461] opened 2016-02-22 01:58 UTC
:rotating_light: game [Rogue's Eye](https://pnjeffries.itch.io/rogues-eye) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/6f8c5250b2c6af7ee86f).

:running: I just ran it for the first time and when I clicked on it, it opened this tab.

**Comment by servel333** [comment] 2016-02-22 01:59
Here is the actual stack trace from the debug log.

```
Error: spawn Unknown system error -88
    at exports._errnoException (util.js:856:11)
    at ChildProcess.spawn (internal/child_process.js:298:11)
    at Object.exports.spawn (child_process.js:374:9)
    at spawn (/Applications/itch.app/Contents/Resources/app.asar/appsrc/util/spawn.js:24:29)
    at Object.<anonymous> (/Applications/itch.app/Contents/Resources/app.asar/appsrc/tasks/launch.js:28:22)
    at [object Generator].next (native)
    at [object Generator].tryCatcher (/Applications/itch.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/util.js:16:23)
    at PromiseSpawn._promiseFulfilled (/Applications/itch.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/generators.js:90:49)
    at Object.<anonymous> (/Applications/itch.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/generators.js:182:15)
    at Object.sh (/Applications/itch.app/Contents/Resources/app.asar/appsrc/tasks/launch.js:19:7)
    at Object.self.launch (/Applications/itch.app/Contents/Resources/app.asar/appsrc/tasks/launch.js:134:19)
    at Object.<anonymous> (/Applications/itch.app/Contents/Resources/app.asar/appsrc/tasks/launch.js:160:17)
    at [object Generator].next (native)
    at [object Generator].tryCatcher (/Applications/itch.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/util.js:16:23)
    at PromiseSpawn._promiseFulfilled (/Applications/itch.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/generators.js:90:49)
    at Promise._settlePromise (/Applications/itch.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/promise.js:560:26)
```

**Comment by fasterthanlime** [comment] 2016-02-22 15:00
duplicate of #452

**Closed as completed by fasterthanlime** 2016-02-22 15:00 UTC
