### ISSUE TITLE
Blank after login

### ISSUE THREAD

**Issue by junklatch** [itchio/itch#592] opened 2016-05-05 18:00 UTC
itch version 16.1.0
Windows 10

So after my late night escapades breaking the itch app by closing tabs as humanly possible, I seemingly further broke the app. After logging in I got this blank screen:

![image](https://cloud.githubusercontent.com/assets/19211259/15051461/ba43c74c-12c6-11e6-9338-66dd41e99ccb.png)

upon restarting the program I'm stuck here

![image](https://cloud.githubusercontent.com/assets/19211259/15051919/0d0b4408-12c9-11e6-967d-146e848565cd.png)

Not sure what I did to upset it :(

**Comment by fasterthanlime** [comment] 2016-05-05 18:27
@junklatch can you press 'Shift-F12' and paste the contents of the console that opens? It should look something like this (lower left):

<img width="1614" alt="screen shot 2016-05-05 at 20 26 55" src="https://cloud.githubusercontent.com/assets/7998310/15052805/c0928dd4-12ff-11e6-8878-59b91c9172f8.png">

**Comment by junklatch** [comment] 2016-05-05 18:32
![image](https://cloud.githubusercontent.com/assets/19211259/15052939/28ea501a-12ce-11e6-9c97-78df011b8b0c.png)
here's what i get

**Comment by fasterthanlime** [comment] 2016-05-06 00:49
@junklatch re-open if not fixed in v17

**Comment by Deozaan** [comment] 2016-05-06 20:49
@fasterthanlime this needs to be reopened. I just encountered this same issue in v17.1.0. The console log is empty for me. But maybe that's because I opened it after the screen was already blank, instead of before I tried logging in?

![blank itch](https://cloud.githubusercontent.com/assets/227734/15085554/439379d0-1398-11e6-8b42-06788039062e.png)

Interestingly, there are still plenty of HTML elements that should be displaying:

![itch blank](https://cloud.githubusercontent.com/assets/227734/15085806/ae2d9bd0-1399-11e6-85a5-c308ac3579c1.gif)

**Comment by fasterthanlime** [comment] 2016-05-06 21:15
@Deozaan can you paste the contents of your `%APPDATA%/itch/users/486/marketdb/itchAppTabs/x` file?

**Comment by Deozaan** [comment] 2016-05-06 21:42
@fasterthanlime I'm not sure if this will be of any use to you, since I closed Itch and restarted it and now it's working properly, so my tabs have changed since I encountered this issue. But here it is:

`{"current":"dd41e0d5-f77f-41a6-aff8-8bddec0cecb8","items":[{"id":"dd41e0d5-f77f-41a6-aff8-8bddec0cecb8","path":"url/https://docs.itch.ovh/itch/"},{"id":"98c78a29-e708-41aa-8898-a3780bcb8f29","path":"url/https://github.com/itchio/itch/issues/214"}]}`

And--not to be pedantic, but just FYI--the file was `%APPDATA%/Roaming/itch/users/486/marketdb/itchAppTabs/x`

**Comment by fasterthanlime** [comment] 2016-05-06 21:46
> And--not to be pedantic, but just FYI--the file was %APPDATA%/Roaming/itch/users/486/marketdb/itchAppTabs/x

Interesting! For me, typing `%APPDATA%` in the Windows 10 file explorer leads me straight to `C:\Users\amos\AppData\Roaming`

**Comment by Deozaan** [comment] 2016-05-06 21:51
> Interesting! For me, typing `%APPDATA%` in the Windows 10 file explorer leads me straight to `C:\Users\amos\AppData\Roaming`

Yep! Once again, you're right and I've made a silly mistake. :) Rather than typing `%APPDATA%` in Explorer, I just browsed my filesystem to the AppData folder in my user directory, which apparently is not the same as `%APPDATA%`.

And, erm... Did you intend to close this issue? Did you find the solution?

**Comment by fasterthanlime** [comment] 2016-05-06 21:52
The blank page thing worries me though. I rewrote most of the tab navigation code between v17.0 and v17.1 but I'm still not happy with it, it's still too brittle.. it rarely happens to me though!

if you do manage to reproduce it, try to remember checking that file. Thanks!

**Comment by Deozaan** [comment] 2016-05-06 21:58
@fasterthanlime OK. I just closed Itch and restarted it, and got the same blank window again after clicking my profile to login. As far as I can tell, everything is the same as the last time I encountered this issue: The error console is blank, HTML elements exist in the source but aren't being displayed (or just have a black box in front of them?), and the `x` tabs file seems to be the same as it was before:

`{"current":"dd41e0d5-f77f-41a6-aff8-8bddec0cecb8","items":[{"id":"dd41e0d5-f77f-41a6-aff8-8bddec0cecb8","path":"url/https://docs.itch.ovh/itch/"},{"id":"98c78a29-e708-41aa-8898-a3780bcb8f29","path":"url/https://github.com/itchio/itch/issues/214"}]}`

What else should I do while I'm sitting here with a (mostly) blank Itch window open to help you track down this bug?

**Comment by fasterthanlime** [comment] 2016-05-06 22:02
@Deozaan you could try launching itch.exe directly from cmd.exe so that you'd see the _other_ app log. (it's in `%APPDATA%\..\Local\itch\app-15.1.0\itch.exe`, off the top of my head)

You could also try pressing `Shift+F5` - that'll reload the browser part of the app and either 1) fix it, or 2) display messages that explain why it's not showing anything.

You could also set the `DEVTOOLS` environment variable to `1` so that dev tools would open before you even click on your name to log in.

**Comment by Deozaan** [comment] 2016-05-06 22:18
OK. Before closing Itch to try launching it directly from `cmd`, I tried `Shift-F5` to reload the browser part of the app. It didn't fix it, and the console log is still blank.

But now my `itchAppTabs/x` file has changed to the following: `{"current":"featured","items":[]}`

After that I closed and relaunched Itch a couple of times (I seem to get the blank window every other time I open Itch) and got the blank window again. Here's the cmd log:

```
C:\Users\Deozaan\AppData\Local\itch\app-17.1.0>itch.exe

C:\Users\Deozaan\AppData\Local\itch\app-17.1.0>
[2016-05-06 @ 16:15:51] [itch] using electron 0.37.7
Creating C:\Users\Deozaan\AppData\Roaming\itch in case it doesn't exist..
[2016-05-06 @ 16:15:51] [preboot] Creating C:\Users\Deozaan\AppData\Roaming\itch in case it doesn't exist..
[2016-05-06 @ 16:15:51] [navigation] Not logged in, not saving tabs yet...
[2016-05-06 @ 16:15:51] [market] loading market db from C:\Users\Deozaan\AppData\Roaming\itch\marketdb
[2016-05-06 @ 16:15:51] [market] cleaning temporary files from C:\Users\Deozaan\AppData\Roaming\itch\marketdb
[2016-05-06 @ 16:15:51] [market] loading records for C:\Users\Deozaan\AppData\Roaming\itch\marketdb
[2016-05-06 @ 16:15:51] [navigation] Not logged in, not saving tabs yet...
[2016-05-06 @ 16:15:51] [locales] Waiting a bit before downloading en locale...
[2016-05-06 @ 16:15:51] [locales] Downloading fresh locale file from http://locales.itch.ovh/itch/en.json
[2016-05-06 @ 16:15:51] [market] migrating old entries for C:\Users\Deozaan\AppData\Roaming\itch\marketdb
[2016-05-06 @ 16:15:51] [market] populating in-memory DB with disk records
[2016-05-06 @ 16:15:51] [market] done loading db from C:\Users\Deozaan\AppData\Roaming\itch\marketdb
[2016-05-06 @ 16:15:51] [preboot] Importing db for user 486
[2016-05-06 @ 16:15:51] [market] closing db C:\Users\Deozaan\AppData\Roaming\itch\marketdb
[2016-05-06 @ 16:15:51] [self-update] Installed!
[2016-05-06 @ 16:15:51] [self-update] Update feed: https://nuts.itch.zone/update/win32_ia32/17.1.0
[2016-05-06 @ 16:15:51] [market] loading market db from C:\Users\Deozaan\AppData\Roaming\itch\marketdb
[2016-05-06 @ 16:15:51] [market] cleaning temporary files from C:\Users\Deozaan\AppData\Roaming\itch\marketdb
(electron) title-bar-style is deprecated. Use titleBarStyle instead.
[2016-05-06 @ 16:15:52] [preferences] imported preferences:
[2016-05-06 @ 16:15:52] [market] loading records for C:\Users\Deozaan\AppData\Roaming\itch\marketdb
[2016-05-06 @ 16:15:52] [preferences] preferences saved (1)
[2016-05-06 @ 16:15:52] [locales] Waiting a bit before downloading en locale...
[2016-05-06 @ 16:15:52] [market] migrating old entries for C:\Users\Deozaan\AppData\Roaming\itch\marketdb
[2016-05-06 @ 16:15:52] [market] populating in-memory DB with disk records
[2016-05-06 @ 16:15:52] [market] done loading db from C:\Users\Deozaan\AppData\Roaming\itch\marketdb
[2016-05-06 @ 16:15:52] [locales] HTTP GET http://locales.itch.ovh/itch/en.json: 200
[2016-05-06 @ 16:15:52] [locales] Saving fresh en locale to C:\Users\Deozaan\AppData\Roaming\itch\locales\en.json
[2016-05-06 @ 16:15:52] [ibrew] 7za: have latest (15.14)
[2016-05-06 @ 16:15:52] [ibrew] elevate: have latest (0.3.2)
[2016-05-06 @ 16:15:52] [ibrew] file: have latest (5.24)
[2016-05-06 @ 16:15:52] [ibrew] butler: have latest (0.14.7)
[2016-05-06 @ 16:15:52] [locales] Downloading fresh locale file from http://locales.itch.ovh/itch/en.json
[2016-05-06 @ 16:15:53] [locales] HTTP GET http://locales.itch.ovh/itch/en.json: 200
[2016-05-06 @ 16:15:53] [locales] Saving fresh en locale to C:\Users\Deozaan\AppData\Roaming\itch\locales\en.json
[2016-05-06 @ 16:15:53] [self-update] Checking...
[2016-05-06 @ 16:15:54] [fetch-saga] Not logged in, not fetching anything yet
[2016-05-06 @ 16:15:54] [navigation] Not logged in, not saving tabs yet...
[2016-05-06 @ 16:15:54] [self-update] HTTP GET https://nuts.itch.zone/update/win32_ia32/17.1.0: 204
[2016-05-06 @ 16:15:56] [fetch-saga] Not logged in, not fetching anything yet
[2016-05-06 @ 16:15:56] [navigation] Not logged in, not saving tabs yet...
[2016-05-06 @ 16:15:57] [market] loading market db from C:\Users\Deozaan\AppData\Roaming\itch\users\486\marketdb
[2016-05-06 @ 16:15:57] [market] cleaning temporary files from C:\Users\Deozaan\AppData\Roaming\itch\users\486\marketdb
[2016-05-06 @ 16:15:57] [fetch-saga] Fetching the usuals
[2016-05-06 @ 16:15:57] [market] loading records for C:\Users\Deozaan\AppData\Roaming\itch\users\486\marketdb
Error in takeEvery "LOGIN_SUCCEEDED": RangeError: Maximum call stack size exceeded
    at String.replace (native)
    at RegExp.<anonymous> (D:\Deozaan\AppData\Local\itch\app-17.1.0\resources\app.asar\node_modules\core-js\modules\_fix-re-wks.js:22:44)
    at String.replace (D:\Deozaan\AppData\Local\itch\app-17.1.0\resources\app.asar\node_modules\core-js\modules\es6.regexp.replace.js:9:12)
    at camelify (D:\Deozaan\AppData\Local\itch\app-17.1.0\resources\app.asar\appsrc\util\format.js:11:14)
    at _underline.map.call (D:\Deozaan\AppData\Local\itch\app-17.1.0\resources\app.asar\appsrc\util\format.js:19:39)
    at _.map._.collect (D:\Deozaan\AppData\Local\itch\app-17.1.0\resources\app.asar\node_modules\underline\node_modules\underscore\underscore.js:172:24)
    at D:\Deozaan\AppData\Local\itch\app-17.1.0\resources\app.asar\node_modules\underline\underline.js:23:14
    at executeBound (D:\Deozaan\AppData\Local\itch\app-17.1.0\resources\app.asar\node_modules\underline\node_modules\underscore\underscore.js:701:67)
    at bound (D:\Deozaan\AppData\Local\itch\app-17.1.0\resources\app.asar\node_modules\underline\node_modules\underscore\underscore.js:733:14)
    at camelifyObject (D:\Deozaan\AppData\Local\itch\app-17.1.0\resources\app.asar\appsrc\util\format.js:19:14)
    at _underline.map.call (D:\Deozaan\AppData\Local\itch\app-17.1.0\resources\app.asar\appsrc\util\format.js:19:54)
    at _.map._.collect (D:\Deozaan\AppData\Local\itch\app-17.1.0\resources\app.asar\node_modules\underline\node_modules\underscore\underscore.js:172:24)
    at D:\Deozaan\AppData\Local\itch\app-17.1.0\resources\app.asar\node_modules\underline\underline.js:23:14
    at executeBound (D:\Deozaan\AppData\Local\itch\app-17.1.0\resources\app.asar\node_modules\underline\node_modules\underscore\underscore.js:701:67)
    at bound (D:\Deozaan\AppData\Local\itch\app-17.1.0\resources\app.asar\node_modules\underline\node_modules\underscore\underscore.js:733:14)
    at camelifyObject (D:\Deozaan\AppData\Local\itch\app-17.1.0\resources\app.asar\appsrc\util\format.js:19:14)
    at _underline.map.call (D:\Deozaan\AppData\Local\itch\app-17.1.0\resources\app.asar\appsrc\util\format.js:19:54)
```

**Comment by fasterthanlime** [comment] 2016-05-06 22:22
```
Error in takeEvery "LOGIN_SUCCEEDED": RangeError: Maximum call stack size exceeded
    at String.replace (native)
    at RegExp.<anonymous> (D:\Deozaan\AppData\Local\itch\app-17.1.0\resources\app.asar\node_modules\core-js\modules\_fix-re-wks.js:22:44)
    at String.replace (D:\Deozaan\AppData\Local\itch\app-17.1.0\resources\app.asar\node_modules\core-js\modules\es6.regexp.replace.js:9:12)
    at camelify (D:\Deozaan\AppData\Local\itch\app-17.1.0\resources\app.asar\appsrc\util\format.js:11:14)
```

Ah, that's super interesting! It looks like `camelifyObject` was called on an object containing a cycle... but it's mostly used to normalize API response, and those can't contain cycles. Hmmmmmm.. I'll keep investigating.

**Comment by Deozaan** [comment] 2016-05-10 07:02
This issue should be reopened. I'm still seeing this behavior every other time I open Itch.

**Comment by fasterthanlime** [comment] 2016-05-10 07:19
> This issue should be reopened. I'm still seeing this behavior every other time I open Itch.

Well, I can add cycle detection in camelifyObject & print the cause when it happens... but it's still pretty strange!

**Comment by fasterthanlime** [comment] 2016-05-30 10:05
Just ran into the camelify bug out of the blue:

https://gist.github.com/fasterthanlime/8e12c86fd8f885afc3dfa8218a0621d1

Can't reproduce by starting the app again, though :(

**Comment by fasterthanlime** [comment] 2016-05-30 10:24
> Can't reproduce by starting the app again, though :(

Actually happens around 1/3rd of the time now, promising!

**Closed as completed** 2016-05-30 10:45 UTC
Labels: bug, critical
