### ISSUE TITLE
[win32] game Ananias Roguelike broken for v0.13.2

### ISSUE THREAD

**Issue by eltorga** [itchio/itch#472] opened 2016-02-26 22:04 UTC
:rotating_light: game [Ananias Roguelike](https://slash.itch.io/ananias) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/33e9ce4d3694c40fbbb3).

:running: Any additional details can go here!

**Comment by fasterthanlime** [comment] 2016-02-27 18:34
Duplicate of #473

**Closed as completed by fasterthanlime** 2016-02-27 18:34 UTC
