### ISSUE TITLE
Download error

### ISSUE THREAD

**Issue by Invent0-r** [itchio/itch#2434] opened 2020-06-13 08:38 UTC
Что-то пошло не так

itch-setup, v1.18.0, built on Apr 10 2019 @ 14:29:17, ref 57838bc373361f2c8938336674247f869999e862

Got HTTP 403 for https://broth.itch.ovh/itch/windows-amd64/LATEST
github.com/itchio/itch-setup/setup.(*Installer).brothGetBytes
	C:/Multi-Runner/builds/58469115/0/itchio/itch-setup/src/github.com/itchio/itch-setup/setup/broth.go:64
github.com/itchio/itch-setup/setup.(*Installer).brothGetString
	C:/Multi-Runner/builds/58469115/0/itchio/itch-setup/src/github.com/itchio/itch-setup/setup/broth.go:76
github.com/itchio/itch-setup/setup.(*Installer).getVersion
	C:/Multi-Runner/builds/58469115/0/itchio/itch-setup/src/github.com/itchio/itch-setup/setup/setup.go:129
github.com/itchio/itch-setup/setup.(*Installer).warmUp
	C:/Multi-Runner/builds/58469115/0/itchio/itch-setup/src/github.com/itchio/itch-setup/setup/setup.go:105
github.com/itchio/itch-setup/setup.(*Installer).WarmUp.func1
	C:/Multi-Runner/builds/58469115/0/itchio/itch-setup/src/github.com/itchio/itch-setup/setup/setup.go:96
runtime.goexit
	C:/Go/src/runtime/asm_amd64.s:1337
while getting latest version
Error during warm-up

**Comment by aktentasche** [comment] 2020-06-15 20:54
Duplicate of #2389

**Closed as completed** 2020-06-16 07:16 UTC
