### ISSUE TITLE
socket hang up

### ISSUE THREAD

**Issue by premek** [itchio/itch#859] opened 2016-08-29 20:02 UTC
I'm geting lot of network errors while trying to update a game, self update the app and sometimes on login.
My network connection may not be the best but normal web browsing is working fine when this happens.
The problems with the update happens _every time_ - never able to update.
Log attached.
Pls let me know if I can try anything or provide better info.

[log.txt](https://github.com/itchio/itch/files/443333/log.txt)

**Comment by premek** [comment] 2016-08-29 20:04
itch ver 18.6.2 on ubuntu

**Comment by fasterthanlime** [comment] 2016-09-02 11:33
Hey, thanks for the report - this sounds like a duplicate of #624. Along with retrying, it looks like I might have to increase the timeout as well.

**Closed as completed by fasterthanlime** 2016-09-02 11:33 UTC
