### ISSUE TITLE
support .unitypackage files 

### ISSUE THREAD

**Issue by selfsame** [itchio/itch#397] opened 2016-01-17 16:25 UTC
itch.io app is sniffing the tar+gz compression in .unitypackage files and auto uncompressing (found issue on windows 7)

**Comment by fasterthanlime** [comment] 2016-01-17 16:42
> itch.io app is sniffing the tar+gz compression in .unitypackage files and auto uncompressing (found issue on windows 7)

As in, when you download an asset pack, itch just unpacked it instead of giving you a usable .unitypackage file?

**Comment by selfsame** [comment] 2016-01-17 16:49
yes, also adding a `.itch` directory inside the unitypackage

**Comment by fasterthanlime** [comment] 2016-06-30 23:03
Doing that now

**Comment by fasterthanlime** [comment] 2016-06-30 23:03
(Was a duplicate of #453)

**Closed as completed by fasterthanlime** 2016-06-30 23:03 UTC
Labels: bug, compatibility
