### ISSUE TITLE
Use a non GNU/Linux distro-specific updater 

### ISSUE THREAD

**Issue by wilcoxm** [itchio/itch#1501] opened 2017-09-06 13:00 UTC
I think it would be best since not all of us have the official distributions (to install/check for updates)

I believe it would be best to install to /opt/itch and allow itch to update itself, this way we can install on any Linux distro and be happy with it.

**Comment by fasterthanlime** [comment] 2017-09-06 13:18
I agree, duplicate of #827 though!

**Closed as completed by fasterthanlime** 2017-09-06 13:18 UTC
