### ISSUE TITLE
[linux] game Sagittarius broken for v0.13.2

### ISSUE THREAD

**Issue by ghost** [itchio/itch#576] opened 2016-04-19 23:33 UTC
:rotating_light: game [Sagittarius](https://gprosser.itch.io/sagittarius) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/2c28a7b80a8bf8fe0973fb2981390426).

:running: Never started up

**Comment by fasterthanlime** [comment] 2016-05-06 20:45
Duplicate of #135

**Closed as completed by fasterthanlime** 2016-05-06 20:45 UTC
