### ISSUE TITLE
No demo link in the itch app

### ISSUE THREAD

**Issue by LiamDawe** [itchio/itch#851] opened 2016-08-12 14:53 UTC
I was notified about this game https://dbetelgeuse.itch.io/orange-moon

It has a demo link when you view by chrome, but not in the itch app itself.

**Comment by fasterthanlime** [comment] 2016-08-12 19:02
Could it be a duplicate of #385 ?

**Comment by LiamDawe** [comment] 2016-08-12 19:03
Looks probable.

**Closed as completed** 2018-06-25 22:05 UTC
