### ISSUE TITLE
[linux] game SpaceHex broken for v0.11.4

### ISSUE THREAD

**Issue by LiamDawe** [itchio/itch#329] opened 2016-01-06 19:23 UTC
:rotating_light: Game [SpaceHex](http://sheepolution.itch.io/spacehex) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/488a0d23306e511b4303).

**Comment by fasterthanlime** [comment] 2016-01-13 12:18
.love files aren't supported yet, duplicate of #135

**Closed as completed by fasterthanlime** 2016-01-13 12:18 UTC
