### ISSUE TITLE
[win32] game skorpulac broken for v0.13.2

### ISSUE THREAD

**Issue by eltorga** [itchio/itch#500] opened 2016-03-03 18:02 UTC
:rotating_light: game [skorpulac](https://aarkipel.itch.io/skorpulac) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/1c1ea2e18f3a2d80228e).

:running: Any additional details can go here!

**Comment by fasterthanlime** [comment] 2016-03-03 19:21
duplicate of #499

**Closed as completed by fasterthanlime** 2016-03-03 19:21 UTC
