### ISSUE TITLE
Top-level crash, net::ERR_CONNECTION_RESET, log included

### ISSUE THREAD

**Issue by ghost** [itchio/itch#1071] opened 2016-12-16 18:40 UTC
(I have read a previous issue that was closed, https://github.com/itchio/itch/issues/1030)
Event log:

```
Error: net::ERR_CONNECTION_RESET
    at Error (native)
```

This sometimes happens during the startup stages of the app, while the application is updating.

The problem is that I have slow internet, and the request is timing out (rather annoying because I cannot get large downloads to finish often). If something could be done for people who suffer from terrible internet, I would be very thankful.

Here is one of the errors in the itch.txt log. It has also happened while `reacting to LOGIN_SUCCEEDED`.
```
[2016-12-16 @ 12:23:38.079] [reactors] while reacting to WINDOW_FOCUS_CHANGED: Error: Request timed out
    at RequestError (C:\Users\Michael\AppData\Local\itch\app-21.0.4\resources\app.asar\appsrc\util\net.ts:24:5)
    at RequestTimeout (C:\Users\Michael\AppData\Local\itch\app-21.0.4\resources\app.asar\appsrc\util\net.ts:30:5)
    at Timeout.setTimeout (C:\Users\Michael\AppData\Local\itch\app-21.0.4\resources\app.asar\appsrc\util\net.ts:139:16)
    at tryOnTimeout (timers.js:232:11)
    at Timer.listOnTimeout (timers.js:202:5)
From previous event:
    at C:\Users\Michael\AppData\Local\itch\app-21.0.4\resources\app.asar\appsrc\reactors\fetch.ts:32:20
    at next (<anonymous>)
    at C:\Users\Michael\AppData\Local\itch\app-21.0.4\resources\app.asar\app\reactors\fetch.js:7:65
    at __awaiter (C:\Users\Michael\AppData\Local\itch\app-21.0.4\resources\app.asar\app\reactors\fetch.js:3:12)
    at fetchUsuals (C:\Users\Michael\AppData\Local\itch\app-21.0.4\resources\app.asar\app\reactors\fetch.js:23:12)
    at C:\Users\Michael\AppData\Local\itch\app-21.0.4\resources\app.asar\appsrc\reactors\debounce.ts:42:25
    at next (<anonymous>)
    at fulfilled (C:\Users\Michael\AppData\Local\itch\app-21.0.4\resources\app.asar\app\reactors\debounce.js:4:58)
```

Best regards,
Michael Musgrove

**Comment by cptodin** [comment] 2017-01-31 18:45
I have a similar issue, I also currently have a rather slow/sketchy internet connection

 itch 23.1.0 on electron 1.4.13
Debian Jessie Linux version 3.16.0-4-amd64 (debian-kernel@lists.debian.org) (gcc version 4.8.4 (Debian 4.8.4-1) ) #1 SMP Debian 3.16.39-1 (2016-12-30)

What I was doing:
Starting itch via terminal, automatic login, wait for about 5 minutes until it crashes

What I expected:
itch starting properly, instead it is stuck after the login screen at "Installing dependency butler 3.4.0"
Screenshot: [https://abload.de/img/screenshotfrom2017-012ojcv.jpg](https://abload.de/img/screenshotfrom2017-012ojcv.jpg)

Event log:

```
redacted@xxx:~$ itch
Gtk-Message: Failed to load module "canberra-gtk-module"
Mounting crash reporter
Fully mounted crash reporter
[2017-01-31 @ 19:19:03.120] [itch] itch 23.1.0 on electron 1.4.13
[2017-01-31 @ 19:19:03.426] [xdg-mime] registering self as default handler for itchio:// protocol
[2017-01-31 @ 19:19:03.429] [spawn] spawning xdg-mime with args default itch.desktop x-scheme-handler/itchio
[2017-01-31 @ 19:19:03.496] [xdg-mime] querying default handler for itchio:// protocol
[2017-01-31 @ 19:19:03.497] [spawn] spawning xdg-mime with args query default x-scheme-handler/itchio
[2017-01-31 @ 19:19:03.527] [locales] Waiting a bit before downloading en locale...
[2017-01-31 @ 19:19:03.539] [xdg-mime] query: itch.desktop
[2017-01-31 @ 19:19:03.541] [preboot] Set up certificate error handler
[2017-01-31 @ 19:19:03.604] [preboot] No proxy detected
[2017-01-31 @ 19:19:03.613] [reactors/setup] setup starting
[2017-01-31 @ 19:19:03.615] [ibrew] Augmenting $PATH: /home/redacted/.config/itch/bin/unarchiver
[2017-01-31 @ 19:19:03.741] [preferences] imported preferences: 
[2017-01-31 @ 19:19:03.744] [reactors/open-at-login] Updating login item settings, open: false, hidden: false
[2017-01-31 @ 19:19:03.744] [reactors/open-at-login] Copying /usr/share/applications/io.itch.itch.desktop => /home/redacted/.config/autostart/io.itch.itch.desktop
[2017-01-31 @ 19:19:03.750] [reactors/main-window] creating main window with icon: /usr/lib/itch/resources/app.asar/app/static/images/window/itch/icon.png
[2017-01-31 @ 19:19:03.751] [reactors/main-window] cf. https://github.com/electron/electron/issues/6205
[2017-01-31 @ 19:19:03.776] [reactors/main-window] Ensuring {"x":0,"y":67,"width":1920,"height":980} is inside a display
[2017-01-31 @ 19:19:03.778] [reactors/main-window] Display bounds: {"x":0,"y":0,"width":1920,"height":1080}
[2017-01-31 @ 19:19:03.778] [reactors/main-window] Bounds unchanged: {"x":0,"y":67,"width":1920,"height":980}
[2017-01-31 @ 19:19:03.784] [reactors/main-window] Calling loadURL
[2017-01-31 @ 19:19:03.892] [reactors/open-at-login] Error while unlinking /home/redacted/.config/autostart/io.itch.itch.desktop: ENOENT: no such file or directory, unlink '/home/redacted/.config/autostart/io.itch.itch.desktop'
[2017-01-31 @ 19:19:04.150] [locales] Waiting a bit before downloading en locale...
[2017-01-31 @ 19:19:04.531] [locales] Downloading fresh locale file from https://locales.itch.ovh/itch/en.json
[2017-01-31 @ 19:19:05.034] [locales] Waiting a bit before downloading en locale...
[2017-01-31 @ 19:19:05.151] [locales] Downloading fresh locale file from https://locales.itch.ovh/itch/en.json
[2017-01-31 @ 19:19:05.861] [reactors/main-window] Ready to show!
[2017-01-31 @ 19:19:05.862] [reactors/main-window] No devtools
[2017-01-31 @ 19:19:05.862] [reactors/main-window] Sending windowReady with id 1
[2017-01-31 @ 19:19:05.868] [market] loading market db from /home/redacted/.config/itch/marketdb
[2017-01-31 @ 19:19:05.868] [market] cleaning temporary files from /home/redacted/.config/itch/marketdb
[2017-01-31 @ 19:19:05.875] [reactors/self-update] Installed!
[2017-01-31 @ 19:19:05.955] [reactors/navigation] Not logged in, not saving tabs yet...
[2017-01-31 @ 19:19:05.979] [reactors/fetch] Not logged in, not fetching anything yet
[2017-01-31 @ 19:19:06.012] [market] loading records for /home/redacted/.config/itch/marketdb
[2017-01-31 @ 19:19:06.024] [reactors/navigation] Not logged in, not saving tabs yet...
[2017-01-31 @ 19:19:06.027] [reactors/navigation] Not logged in, not saving tabs yet...
[2017-01-31 @ 19:19:06.044] [locales] Downloading fresh locale file from https://locales.itch.ovh/itch/en.json
[2017-01-31 @ 19:19:06.082] [market] populating in-memory DB with disk records
[2017-01-31 @ 19:19:06.097] [market] done loading db from /home/redacted/.config/itch/marketdb
[2017-01-31 @ 19:19:06.177] [reactors/self-update] Update feed: https://nuts.itch.zone/update/deb_x64/23.1.0
[2017-01-31 @ 19:19:06.652] [diego] diego here, looking around
Linux xxx 3.16.0-4-amd64 #1 SMP Debian 3.16.39-1 (2016-12-30) x86_64 GNU/Linux
model name	: Intel(R) Core(TM) i5-4210U CPU @ 1.70GHz
model name	: Intel(R) Core(TM) i5-4210U CPU @ 1.70GHz
model name	: Intel(R) Core(TM) i5-4210U CPU @ 1.70GHz
model name	: Intel(R) Core(TM) i5-4210U CPU @ 1.70GHz
Distributor ID:	Debian
Description:	Debian GNU/Linux 8.7 (jessie)
Release:	8.7
Codename:	jessie
00:02.0 VGA compatible controller: Intel Corporation Haswell-ULT Integrated Graphics Controller (rev 0b)
diego out

[2017-01-31 @ 19:19:08.179] [reactors/self-update] Checking...
[2017-01-31 @ 19:19:09.021] [ibrew] unarchiver: have latest (1.10.1)
[2017-01-31 @ 19:19:09.023] [reactors/setup] unarchiver done
[2017-01-31 @ 19:19:09.023] [ibrew] Augmenting $PATH: /home/redacted/.config/itch/bin
[2017-01-31 @ 19:19:09.046] [locales] HTTP GET https://locales.itch.ovh/itch/en.json: 200
[2017-01-31 @ 19:19:09.047] [locales] Saving fresh en locale to /home/redacted/.config/itch/locales/en.json
[2017-01-31 @ 19:19:09.049] [locales] HTTP GET https://locales.itch.ovh/itch/en.json: 200
[2017-01-31 @ 19:19:09.049] [locales] Saving fresh en locale to /home/redacted/.config/itch/locales/en.json
[2017-01-31 @ 19:19:09.051] [locales] HTTP GET https://locales.itch.ovh/itch/en.json: 200
[2017-01-31 @ 19:19:09.051] [locales] Saving fresh en locale to /home/redacted/.config/itch/locales/en.json
[2017-01-31 @ 19:19:09.875] [ibrew] butler: upgrading '3.3.0' => '3.4.0'
[2017-01-31 @ 19:19:09.878] [ibrew] butler: downloading '3.4.0' from https://dl.itch.ovh/butler/linux-amd64/v3.4.0/butler.7z
[2017-01-31 @ 19:19:09.932] [ibrew] firejail: have latest (0.9.41)
[2017-01-31 @ 19:19:11.508] [market] loading market db from /home/redacted/.config/itch/users/338032/marketdb
[2017-01-31 @ 19:19:11.508] [market] cleaning temporary files from /home/redacted/.config/itch/users/338032/marketdb
[2017-01-31 @ 19:19:11.517] [market] loading records for /home/redacted/.config/itch/users/338032/marketdb
[2017-01-31 @ 19:19:11.672] [reactors/self-update] HTTP GET https://nuts.itch.zone/update/deb_x64/23.1.0: 204
[2017-01-31 @ 19:19:11.735] [market] populating in-memory DB with disk records
[2017-01-31 @ 19:19:11.778] [market] done loading db from /home/redacted/.config/itch/users/338032/marketdb
[2017-01-31 @ 19:19:11.778] [navigation] got user db ready
[2017-01-31 @ 19:19:11.811] [reactors/fetch] Fetching the usuals
[2017-01-31 @ 19:20:13.508] [reactors/navigation] Not logged in, not saving tabs yet...
[2017-01-31 @ 19:20:13.771] [reactors/fetch] Fetching the usuals
[2017-01-31 @ 19:21:19.774] [reactors/navigation] Not logged in, not saving tabs yet...
[2017-01-31 @ 19:21:20.025] [reactors/fetch] Fetching the usuals
[2017-01-31 @ 19:21:21.900] [reactors/navigation] Not logged in, not saving tabs yet...
[2017-01-31 @ 19:21:22.179] [reactors/fetch] Fetching the usuals
[2017-01-31 @ 19:21:32.337] [reactors] while reacting to WINDOW_FOCUS_CHANGED: Error: Request timed out
    at RequestError (/usr/lib/itch/resources/app.asar/appsrc/util/net.ts:24:5)
    at RequestTimeout (/usr/lib/itch/resources/app.asar/appsrc/util/net.ts:30:5)
    at Timeout.setTimeout (/usr/lib/itch/resources/app.asar/appsrc/util/net.ts:139:16)
    at tryOnTimeout (timers.js:232:11)
    at Timer.listOnTimeout (timers.js:202:5)
From previous event:
    at /usr/lib/itch/resources/app.asar/appsrc/reactors/fetch.ts:33:20
    at next (<anonymous>)
    at /usr/lib/itch/resources/app.asar/app/reactors/fetch.js:7:65
    at __awaiter (/usr/lib/itch/resources/app.asar/app/reactors/fetch.js:3:12)
    at fetchUsuals (/usr/lib/itch/resources/app.asar/app/reactors/fetch.js:23:12)
    at /usr/lib/itch/resources/app.asar/appsrc/reactors/debounce.ts:42:25
    at next (<anonymous>)
    at fulfilled (/usr/lib/itch/resources/app.asar/app/reactors/debounce.js:4:58)
[2017-01-31 @ 19:22:07.945] [reactors/navigation] Not logged in, not saving tabs yet...
[2017-01-31 @ 19:22:08.228] [reactors/fetch] Fetching the usuals
[2017-01-31 @ 19:25:06.623] [reactors/navigation] Not logged in, not saving tabs yet...
[2017-01-31 @ 19:25:06.867] [reactors/fetch] Fetching the usuals
[2017-01-31 @ 19:25:17.026] [reactors] while reacting to WINDOW_FOCUS_CHANGED: Error: Request timed out
    at RequestError (/usr/lib/itch/resources/app.asar/appsrc/util/net.ts:24:5)
    at RequestTimeout (/usr/lib/itch/resources/app.asar/appsrc/util/net.ts:30:5)
    at Timeout.setTimeout (/usr/lib/itch/resources/app.asar/appsrc/util/net.ts:139:16)
    at tryOnTimeout (timers.js:232:11)
    at Timer.listOnTimeout (timers.js:202:5)
From previous event:
    at /usr/lib/itch/resources/app.asar/appsrc/reactors/fetch.ts:33:20
    at next (<anonymous>)
    at /usr/lib/itch/resources/app.asar/app/reactors/fetch.js:7:65
    at __awaiter (/usr/lib/itch/resources/app.asar/app/reactors/fetch.js:3:12)
    at fetchUsuals (/usr/lib/itch/resources/app.asar/app/reactors/fetch.js:23:12)
    at /usr/lib/itch/resources/app.asar/appsrc/reactors/debounce.ts:42:25
    at next (<anonymous>)
    at fulfilled (/usr/lib/itch/resources/app.asar/app/reactors/debounce.js:4:58)
[2017-01-31 @ 19:25:36.612] [reactors/navigation] Not logged in, not saving tabs yet...
[2017-01-31 @ 19:25:36.880] [reactors/fetch] Fetching the usuals
[2017-01-31 @ 19:25:47.019] [reactors] while reacting to WINDOW_FOCUS_CHANGED: Error: Request timed out
    at RequestError (/usr/lib/itch/resources/app.asar/appsrc/util/net.ts:24:5)
    at RequestTimeout (/usr/lib/itch/resources/app.asar/appsrc/util/net.ts:30:5)
    at Timeout.setTimeout (/usr/lib/itch/resources/app.asar/appsrc/util/net.ts:139:16)
    at tryOnTimeout (timers.js:232:11)
    at Timer.listOnTimeout (timers.js:202:5)
From previous event:
    at /usr/lib/itch/resources/app.asar/appsrc/reactors/fetch.ts:33:20
    at next (<anonymous>)
    at /usr/lib/itch/resources/app.asar/app/reactors/fetch.js:7:65
    at __awaiter (/usr/lib/itch/resources/app.asar/app/reactors/fetch.js:3:12)
    at fetchUsuals (/usr/lib/itch/resources/app.asar/app/reactors/fetch.js:23:12)
    at /usr/lib/itch/resources/app.asar/appsrc/reactors/debounce.ts:42:25
    at next (<anonymous>)
    at fulfilled (/usr/lib/itch/resources/app.asar/app/reactors/debounce.js:4:58)
Uncaught exception: Error: net::ERR_CONNECTION_CLOSED
    at Error (native)
```

**Comment by fasterthanlime** [comment] 2017-02-01 12:19
@cptodin what tabs did you have open at the time of the crash? I'm trying to reproduce, but anything from reactors/fetch seems to be caught correctly, with just a log entry, not an app crash.

**Comment by fasterthanlime** [comment] 2017-02-01 12:39
> The problem is that I have slow internet, and the request is timing out (rather annoying because I cannot get large downloads to finish often). If something could be done for people who suffer from terrible internet, I would be very thankful.

Note that I did make the downloader ([butler](https://github.com/itchio/butler)) more resilient to network errors a while ago, so that side should be fixed. The app crashing is another matter though, let's hope we can track it down & solve it!

**Comment by cptodin** [comment] 2017-02-01 13:27
I tried again today, with a slightly better internet connection. I do think that this crash might be related to connectivity though. It got stuck at
```

[2017-02-01 @ 14:18:14.364] [reactors/fetch] Fetching the usuals
[2017-02-01 @ 14:18:16.841] [reactors/self-update] HTTP GET https://nuts.itch.zone/update/deb_x64/23.1.0: 204
[2017-02-01 @ 14:19:54.965] [reactors/navigation] Not logged in, not saving tabs yet...
[2017-02-01 @ 14:19:55.214] [reactors/fetch] Fetching the usuals
[2017-02-01 @ 14:20:12.793] [reactors/navigation] Not logged in, not saving tabs yet...
[2017-02-01 @ 14:20:13.075] [reactors/fetch] Fetching the usuals
```

for a while but eventually got through and presented me the interface

Previously I couldn't even get to the tabs, it got stuck before I got any interactivity (see screenshot in my previous post, that's where it got stuck and crashed eventually after a few minutes)

EDIT: I just saw that butler got an update while I was getting above results

```
[2017-02-01 @ 14:18:14.176] [ibrew] firejail: have latest (0.9.41)
[2017-02-01 @ 14:18:14.257] [ibrew] butler: upgrading '3.3.0' => '3.4.0'
[2017-02-01 @ 14:18:14.259] [ibrew] butler: downloading '3.4.0' from https://dl.itch.ovh/butler/linux-amd64/v3.4.0/butler.7z
```

**Comment by fasterthanlime** [comment] 2017-02-01 13:37
> it got stuck for a while

yeah, I'm not happy about that.

To give you some insight, here's what happens:

  * The itch app needs some helper programs to run ('dependencies') - it knows how to install & update them itself
  * When you start up the app, it checks that all those helper programs are present & up-to-date, otherwise it updates them (the "Making sure everything is ready" phase in the UI)
  * If while doing that, it sees that there's no internet at all, it just skips it (along with login) and bring you straight to the library
  * However, if you *do* have internet but it's just super slow/flaky, it'll keep trying and it might take a while.

Here's what I'd like to change it to instead:

  * If all needed helper programs are there, go straight to the "useful UI"
  * Do update checks for those in the background
  * Be smart enough to update dependencies while they're not being used (between downloads/extracts/game launches/etc.)

I already have an idea in mind for that, "just" need to implement it. Let's hope I don't break everything though :)

Note that, when you do have a somewhat-decent connection, the dependencies update check phase takes 1s at most (and it runs concurrently with stuff like loading the local DB) - so it doesn't slow app startup that much. For most users at least.

**Comment by cptodin** [comment] 2017-02-01 13:50
Thanks for the insight, figured that must have happened to me only now the update completed successfully

> Here's what I'd like to change it to instead:
>[…]

That sounds great. I hope it will not crash when it tries to update everything in the background then as it did in my case here

**Comment by fasterthanlime** [comment] 2017-02-01 13:52
> That sounds great. I hope it will not crash when it tries to update everything in the background then as it did in my case here

It's certainly designed not to do that - the fact that it crashed for you and the OP is a distinct bug that I really want to solve too (no exception should be uncaught, ever) - but unfortunately I'm not able to reproduce it at the moment, and can't think of any smart way to find it. I'll keep looking.

**Closed as completed** 2018-09-13 13:06 UTC
