### ISSUE TITLE
Cannot install itch app: Uable to save shortcut

### ISSUE THREAD

**Issue by legenary** [itchio/itch#2445] opened 2020-06-16 05:25 UTC
Something went wrong

itch-setup, v1.18.0, built on Apr 10 2019 @ 06:28:23, ref 57838bc373361f2c8938336674247f869999e862

Exception occurred. (Unable to save shortcut "C:\Users\yiful\OneDrive\??\itch.lnk".)
while creating shortcut

**Comment by fasterthanlime** [comment] 2020-06-16 17:21
I've just released a new version of itch-setup that addresses that issue (a duplicate of #2330).

Can you download the installer from https://itch.io/app and try again?

**Closed as completed by fasterthanlime** 2020-06-16 17:21 UTC
