### ISSUE TITLE
🏁 Issue v23.4.1

### ISSUE THREAD

**Issue by tfaehnle** [itchio/itch#1325] opened 2017-07-14 12:53 UTC
When attempting to log in with a new account before confirming one's email address, login fails with a cryptic js related error message.

Expected behavior would be to tell the user either to verify their account or simply bad username/password, etc.

error shown as follows:

Error: HTTP 404 /login
    at Client.<anonymous> (C:\Users\Username\AppData\Local\itch\app-23.4.1\resources\app.asar\appsrc\util\api.ts:87:13)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\Username\AppData\Local\itch\app-23.4.1\resources\app.asar\app\util\api.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:103:7)

**Comment by fasterthanlime** [comment] 2017-07-14 12:54
> When attempting to log in with a new account before confirming one's email address, login fails with a cryptic js related error message.

Very likely a duplicate of https://github.com/itchio/itch.io/issues/679 - looks like there was a server issue for a few minutes. You can definitely log in with a non-verified account.

**Closed as completed by fasterthanlime** 2017-07-14 12:54 UTC
