### ISSUE TITLE
[linux] game A Skin of Others broken for v0.13.2

### ISSUE THREAD

**Issue by LiamDawe** [itchio/itch#418] opened 2016-01-23 23:25 UTC
:rotating_light: game [A Skin of Others](http://lyeeedar.itch.io/a-skin-of-others) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/5583ef3674957eca83b3).

**Comment by fasterthanlime** [comment] 2016-01-24 11:22
Duplicate of #134

**Closed as completed by fasterthanlime** 2016-01-24 11:22 UTC
