### ISSUE TITLE
Tiled Map Editor Not Downloading

### ISSUE THREAD

**Issue by JetLennit** [itchio/itch#605] opened 2016-05-06 03:40 UTC
For some reason any time I try and download Tiled Map Editor refuses to download for me. I am on a 2011(ish) MacBook Pro running OS X Yosemite. Any time I hit the Install button it goes to downloading for about a half a second and then it goes back to saying Install. Let me know if there is any other information I need to provide.

**Comment by fasterthanlime** [comment] 2016-05-06 07:19
Actually a duplicate of #600, v17 is choking on external uploads. I'll work on a fix.

**Closed as completed** 2016-05-06 07:32 UTC

**Comment by bjorn** [comment] 2016-05-06 11:59
With itch 17.1 I can now download/install Tiled, but it won't launch. The itch output shows:

```
[2016-05-06 @ 13:50:15] [sagas/tasks] Have a cave for game 28768, launching
[2016-05-06 @ 13:50:15] [sagas/tasks] Starting cave aa79955e-822d-49ce-8497-9297879e8a14: stub
[2016-05-06 @ 13:50:15] [sagas/tasks] About to start launch (83345f65-1ca0-4f25-ab90-4714f96861b5)
[2016-05-06 @ 13:50:15] [sagas/tasks] Starting launch (83345f65-1ca0-4f25-ab90-4714f96861b5)...
should configure: stub
[2016-05-06 @ 13:50:15] [sagas/tasks] Task threw
[2016-05-06 @ 13:50:15] [sagas/tasks] Task ended, err: Error: game.install.could_not_launch
    at C:\Users\bjorn\AppData\Local\itch\app-17.1.0\resources\app.asar\appsrc\tasks\launch.js:56:17
    at undefined.next (native)
    at undefined.tryCatcher (C:\Users\bjorn\AppData\Local\itch\app-17.1.0\resources\app.asar\node_modules\bluebird\js\release\util.js:16:23)
    at PromiseSpawn._promiseFulfilled (C:\Users\bjorn\AppData\Local\itch\app-17.1.0\resources\app.asar\node_modules\bluebird\js\release\generators.js:97:49)
    at C:\Users\bjorn\AppData\Local\itch\app-17.1.0\resources\app.asar\node_modules\bluebird\js\release\generators.js:197:15
    at start (C:\Users\bjorn\AppData\Local\itch\app-17.1.0\resources\app.asar\app\tasks\launch.js:112:16)
    at runCallEffect (C:\Users\bjorn\AppData\Local\itch\app-17.1.0\resources\app.asar\node_modules\redux-saga\lib\internal\proc.js:422:19)
    at runEffect (C:\Users\bjorn\AppData\Local\itch\app-17.1.0\resources\app.asar\node_modules\redux-saga\lib\internal\proc.js:352:399)
    at C:\Users\bjorn\AppData\Local\itch\app-17.1.0\resources\app.asar\node_modules\redux-saga\lib\internal\proc.js:605:14
    at Array.forEach (native)
    at runRaceEffect (C:\Users\bjorn\AppData\Local\itch\app-17.1.0\resources\app.asar\node_modules\redux-saga\lib\internal\proc.js:604:10)
    at runEffect (C:\Users\bjorn\AppData\Local\itch\app-17.1.0\resources\app.asar\node_modules\redux-saga\lib\internal\proc.js:352:304)
    at next (C:\Users\bjorn\AppData\Local\itch\app-17.1.0\resources\app.asar\node_modules\redux-saga\lib\internal\proc.js:248:9)
    at currCb (C:\Users\bjorn\AppData\Local\itch\app-17.1.0\resources\app.asar\node_modules\redux-saga\lib\internal\proc.js:308:7)
    at runSelectEffect (C:\Users\bjorn\AppData\Local\itch\app-17.1.0\resources\app.asar\node_modules\redux-saga\lib\internal\proc.js:615:7)
    at runEffect (C:\Users\bjorn\AppData\Local\itch\app-17.1.0\resources\app.asar\node_modules\redux-saga\lib\internal\proc.js:352:848)
[2016-05-06 @ 13:50:15] [sagas/tasks] Error in task launch: Error: game.install.could_not_launch
```

It's probably a problem with the MSI installer, or the way it is invoked, because I can't find where Tiled would be installed (I've tried to click "Open installation folder", but it takes my browser to https://gist.github.com/fasterthanlime/fc0116df32b53c7939016afe0d26796d instead).

**Comment by bjorn** [comment] 2016-05-06 12:03
Ok I guess the problem with the installer is issue #536 (edit: confirmed, when running itch as administrator it works).
