### ISSUE TITLE
[win32] game Double Kick Heroes broken for v0.13.2

### ISSUE THREAD

**Issue by alfblack** [itchio/itch#545] opened 2016-04-07 04:13 UTC
:rotating_light: game [Double Kick Heroes](https://headbangclub.itch.io/double-kick-heroes) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/5c5e028269da8bd5e2f8cc1769ffbcfb).

:running: Any additional details can go here!

**Comment by fasterthanlime** [comment] 2016-05-06 16:59
Duplicate of #370

**Closed as completed by fasterthanlime** 2016-05-06 16:59 UTC
