### ISSUE TITLE
AUR asks for password on `makepkg`

### ISSUE THREAD

**Issue by josefnpat** [itchio/itch#697] opened 2016-06-13 19:38 UTC
https://aur.archlinux.org/packages/itch/#comment-550531

```
==> Starting build()...
Fetching gem metadata from https://rubygems.org/
Fetching version metadata from https://rubygems.org/
Fetching dependency metadata from https://rubygems.org/


Your user account isn't allowed to install to the system Rubygems.
  You can cancel this installation and run:

      bundle install --path vendor/bundle

  to install the gems into ./vendor/bundle/, or you can enter your password
  and install the bundled gems to Rubygems using sudo.

  Password: 
```

Not sure if this is part of the aur, or the build process, but I think there should be dependency resolution here - it shouldn't ask you to install stuff otherwise. Either ruby should install the gem locally, or my package manager (pacman) should install it.

**Comment by josefnpat** [comment] 2016-06-13 19:38
v17.6.6

**Comment by fasterthanlime** [comment] 2016-06-14 09:39
Haven't addressed this yet but: I wrote the ruby scripts mostly for the CI, didn't realize it would be part of the AUR script when writing it 🐙 — on the CI machines, the ruby install used is set via chruby and doesn't need root access to install anything. However the AUR package souldn't assume that all users have that particular setup.

I'm wondering if adding a `--path` argument somewhere is enough or if we'll just have to rewrite the ruby script to bash just for AUR (which would be annoying)

**Comment by fasterthanlime** [comment] 2016-07-07 19:14
Just committed something that should help with that, giving it a few pokes to make sure it's ready to ship with 18.3.0

**Comment by fasterthanlime** [comment] 2016-07-07 21:41
Looks like the new strategy is working (after fixing a PATH mistake). Should be shipping soon.

**Comment by fasterthanlime** [comment] 2016-07-10 11:22
So I spent an entire day messing around, trying to make the ruby scripts less weird and more universal so the PKGBUILD would execute without problems on different ArchLinux versions, but now I'm out of ideas - the latest error is:

```
==> Starting build()...
+ export BUNDLE_PATH=/builds/itchio/itch/aur-stage/src/itch-18.2.4-canary/vendor/bundle
+ BUNDLE_PATH=/builds/itchio/itch/aur-stage/src/itch-18.2.4-canary/vendor/bundle
+ export GEM_HOME=/builds/itchio/itch/aur-stage/src/itch-18.2.4-canary/vendor/bundle
+ GEM_HOME=/builds/itchio/itch/aur-stage/src/itch-18.2.4-canary/vendor/bundle
+ which bundler
/usr/bin/bundler
+ mkdir -p /builds/itchio/itch/aur-stage/src/itch-18.2.4-canary/vendor/bundle
++ ruby -e 'print Gem.user_dir'
/home/itch/.gem/ruby/2.3.0/gems/bundler-1.12.5/lib/bundler/spec_set.rb:95:in `block in materialize': Could not find archive-tar-minitar-0.5.2 in any of the sources (Bundler::GemNotFound)
    from /home/itch/.gem/ruby/2.3.0/gems/bundler-1.12.5/lib/bundler/spec_set.rb:88:in `map!'
    from /home/itch/.gem/ruby/2.3.0/gems/bundler-1.12.5/lib/bundler/spec_set.rb:88:in `materialize'
    from /home/itch/.gem/ruby/2.3.0/gems/bundler-1.12.5/lib/bundler/definition.rb:140:in `specs'
    from /home/itch/.gem/ruby/2.3.0/gems/bundler-1.12.5/lib/bundler/definition.rb:185:in `specs_for'
    from /home/itch/.gem/ruby/2.3.0/gems/bundler-1.12.5/lib/bundler/definition.rb:174:in `requested_specs'
    from /home/itch/.gem/ruby/2.3.0/gems/bundler-1.12.5/lib/bundler/environment.rb:19:in `requested_specs'
    from /home/itch/.gem/ruby/2.3.0/gems/bundler-1.12.5/lib/bundler/runtime.rb:14:in `setup'
    from /home/itch/.gem/ruby/2.3.0/gems/bundler-1.12.5/lib/bundler.rb:95:in `setup'
    from /home/itch/.gem/ruby/2.3.0/gems/bundler-1.12.5/lib/bundler/setup.rb:19:in `<top (required)>'
    from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
+ export PATH=/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/builds/itchio/itch/aur-stage/src/itch-18.2.4-canary/vendor/bundle/bin:/bin
+ PATH=/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/builds/itchio/itch/aur-stage/src/itch-18.2.4-canary/vendor/bundle/bin:/bin
+ export LC_ALL=en_US.UTF-8
+ LC_ALL=en_US.UTF-8
+ export LANGUAGE=en_US.UTF-8
+ LANGUAGE=en_US.UTF-8
+ export LANG=en_US.UTF-8
+ LANG=en_US.UTF-8
+ bundle install
/home/itch/.gem/ruby/2.3.0/gems/bundler-1.12.5/lib/bundler/spec_set.rb:95:in `block in materialize': Could not find archive-tar-minitar-0.5.2 in any of the sources (Bundler::GemNotFound)
    from /home/itch/.gem/ruby/2.3.0/gems/bundler-1.12.5/lib/bundler/spec_set.rb:88:in `map!'
    from /home/itch/.gem/ruby/2.3.0/gems/bundler-1.12.5/lib/bundler/spec_set.rb:88:in `materialize'
    from /home/itch/.gem/ruby/2.3.0/gems/bundler-1.12.5/lib/bundler/definition.rb:140:in `specs'
    from /home/itch/.gem/ruby/2.3.0/gems/bundler-1.12.5/lib/bundler/definition.rb:185:in `specs_for'
    from /home/itch/.gem/ruby/2.3.0/gems/bundler-1.12.5/lib/bundler/definition.rb:174:in `requested_specs'
    from /home/itch/.gem/ruby/2.3.0/gems/bundler-1.12.5/lib/bundler/environment.rb:19:in `requested_specs'
    from /home/itch/.gem/ruby/2.3.0/gems/bundler-1.12.5/lib/bundler/runtime.rb:14:in `setup'
    from /home/itch/.gem/ruby/2.3.0/gems/bundler-1.12.5/lib/bundler.rb:95:in `setup'
    from /home/itch/.gem/ruby/2.3.0/gems/bundler-1.12.5/lib/bundler/setup.rb:19:in `<top (required)>'
    from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
==> ERROR: A failure occurred in build().
    Aborting...
/builds/itchio/itch/release/common.rb:157:in `✓': Non-zero exit code (false), bailing out (RuntimeError)
    from release/ci-package-aur.rb:48:in `block in ci_deploy_aur'
    from /builds/itchio/itch/release/common.rb:201:in `block in cd'
    from /builds/itchio/itch/release/common.rb:200:in `chdir'
    from /builds/itchio/itch/release/common.rb:200:in `cd'
    from release/ci-package-aur.rb:37:in `ci_deploy_aur'
    from release/ci-package-aur.rb:64:in `<main>'
```

As you can see, any ruby command (`ruby -e "print Gem.user_dir"`) and even `bundle install` raises that error now. At this point I need to stop trying to guess and run it into an ArchLinux VM myself, but if someone has even the slightest idea what's going on, I'm happy to hear about it.

I wish distributions wouldn't mess with language runtimes so much :(

**Comment by fasterthanlime** [comment] 2016-07-10 11:22
Link to full failing CI log: https://gist.github.com/fasterthanlime/53ae9dd1738335b4579f6b6a0e398dd4

**Comment by Tele42** [comment] 2016-07-10 12:36
Hello, please forgive me for sticking my nose where it does not belong, as I am not an Arch user, but it appears like you're trying to treat ruby gems like a special dependency. You should be asking for the ruby gem module to get put into the system before trying to build your package like any other dependency.

It looks like you are failing at a missing ruby archive-tar-minitar dependency, which is available in the aur at https://aur.archlinux.org/packages/ruby-archive-tar-minitar/.

Additionally, the original issue appears to be an attempt to use `bundle install` to bypass the package manager and directly install system files from inside Arch's package builder, which should be a security violation. The expectation should be that all sane package managers do not allow for system files to be changed or written outside of the build sandbox.

The distinction here is that all files to be installed to the system go to a staging folder, and the package manager does all it's normal sanity checks like checking for file conflicts as well as generating a file manifest so that the package can later be removed. Other dependency managers like ruby's bundler bypass the package manager and push files into the system without the package manager being involved, which is fine for individual system admin's to choose to do to their own systems, but not okay for package maintainers to do to other people's systems.

**Comment by fasterthanlime** [comment] 2016-07-10 13:35
> Hello, please forgive me for sticking my nose where it does not belong

All are welcome :) :+1:

> It looks like you are failing at a missing ruby archive-tar-minitar dependency, which is available in the aur at https://aur.archlinux.org/packages/ruby-archive-tar-minitar/.

I should've mentioned that the build runs successfully in many other environments, for example in our three types of CI workers (Ubuntu 16.04, macOS, and Windows 2012 server with msys2), so the Gemfile / bundle setup is sound, as far as I can tell. The error here is probably a red herring, due to a conflict between "how ruby is setup in ArchLinux by default" and how I expect to be able to use it.

> The expectation should be that all sane package managers do not allow for system files to be changed or written outside of the build sandbox.

That's precisely why I'm trying to install them in a local directory, `vendor/bundle` :) That's what the ruby package manager `bundler` allows! I wouldn't try to touch system files during PKGBUILD's build() phase.

I completely agree that regular software shouldn't be allowed to write to system files — most distributions' solutions to that is "put it in a package, let the package manager handle it", but this doesn't scale for us. Other people's solution (I fall that category) is: bundle our dependencies, make our software work no matter what environment it's run it. Some have objections against this, I understand both viewpoints.

At any rate, I think I'm tired of fighting against ruby and its various incarnations on various Linux distributions: I think I'll rewrite all `release/ci-*.rb` scripts to use node.js instead, since the app already requires it. As a result, the AUR package will no longer require ruby, and node.js's package manager (while I have many many other complaints about it) at least installs to a local folder (`node_modules`) by default, and has much fewer paths / environment variables to worry about.

**Comment by fasterthanlime** [comment] 2016-07-10 13:37
(note: I don't expect everybody contributing to be an expert on the subject and I realize this issue is missing a lot of context / previous research — I hope my response doesn't come off as too dismissive! changing tools here seems like the less costly option, except for dropping AUR support, which isn't something I'm willing to do.)

**Comment by fasterthanlime** [comment] 2016-07-12 00:04
Have now ported about 90% of our ci scripts to javascript, looking forward to remove all dependencies on ruby.

**Comment by fasterthanlime** [comment] 2016-07-12 12:27
Phew! The AUR build is succeeding again: https://gist.github.com/fasterthanlime/6cd9673aca636eb171f934e4a8a90906

**Comment by josefnpat** [comment] 2016-07-12 16:17
Sweet! Thank you! I don't have an Arch machine to test it on atm, so unless you want to wait a month for me to get back to it, either wait for an arch user to chime in, or just close the ticket :)

**Comment by fasterthanlime** [comment] 2016-07-27 12:59
Finally managed to get an ArchLinux VM running, I can confirm 18.4.0 installs correctly, without asking for root password or filling `~/.bundle`. The only thing missing is a dependency on `libxss`.

![yaourt-s-itch](https://cloud.githubusercontent.com/assets/7998310/17175824/f85c2324-5409-11e6-9c3c-e6d6661afe32.png)

![downloading](https://cloud.githubusercontent.com/assets/7998310/17175851/168abfe0-540a-11e6-89a2-b0c912e97f45.png)

**Closed as completed by fasterthanlime** 2016-07-27 12:59 UTC
Labels: linux
