### ISSUE TITLE
after logging in, the browser window should refresh to show it

### ISSUE THREAD

**Issue by LiamDawe** [itchio/itch#709] opened 2016-06-16 18:23 UTC
So one thing that could do with sprucing up a bit is the Login. You login to the app, but you still need to Login to the store in the in-built browser. Not a major issue since it grabs your username, but annoying.

After this, it loaded up my feed, but going back to the store still showed me as logged out until I refreshed it.

**Comment by fasterthanlime** [comment] 2016-06-17 07:03
Good point! but closing as it is a duplicate of #672 (see that issue for an explanation of why it's not done yet)

**Closed as completed by fasterthanlime** 2016-06-17 07:03 UTC
