### ISSUE TITLE
Keep download progress after quit

### ISSUE THREAD

**Issue by buckle2000** [itchio/itch#1160] opened 2017-03-17 15:28 UTC
Well, please make the app remember downloading items when quitting.

**Comment by fasterthanlime** [comment] 2017-03-17 15:42
Just to clarify the current state of things:

  * On app quit, current downloads are "forgotten" ...
  * ... but the partial downloads are still on disk
  * So, manually starting the donwload again will resume them

**Comment by sigmap** [comment] 2017-08-12 23:48
I would very much appreciate this feature and it would make the itch desktop client more attractive to users and especially steam users.

**Comment by fasterthanlime** [comment] 2018-01-27 12:16
Marking as duplicate of #1465

**Closed as completed by fasterthanlime** 2018-01-27 12:16 UTC
Labels: ui / ux
