### ISSUE TITLE
[blue sky suggestion] Collections icons/covers

### ISSUE THREAD

**Issue by junklatch** [itchio/itch#636] opened 2016-05-09 03:24 UTC
Maybe someday Collections could be represented by squares that show previews of the individual games? iTunes style maybe?
![image](https://cloud.githubusercontent.com/assets/19211259/15102975/f5e0014e-1573-11e6-86cc-bc5b2efb832c.png)

Maybe just something a little more visual/ consistent with the game navigation UI

**Comment by fasterthanlime** [comment] 2016-05-09 10:52
duplicate of #615 but I'll allow it because of that magnificent playlist name

**Closed as completed** 2016-06-23 17:53 UTC
Labels: ui / ux
