### ISSUE TITLE
Support upgrading games via sequence of patches

### ISSUE THREAD

**Issue by quyse** [itchio/itch#935] opened 2016-10-06 19:57 UTC
Currently itch doesn't support downloading multiple patches and applying them one by one in a sequence. So if I have a 1.1 version of a game installed locally, missed upgrade to version 1.2, and started itch when version 1.3 already arrived, itch is going to fully download brand new copy of the game v1.3.

It makes sense to download and apply sequence of patches if they are smaller than a full copy (here traffic is always more important than processing time, isn't it). Multiple patches are not going to take a lot of additional space on itch.io servers, because you can keep uploaded patches only until their total size exceed size of from-scratch-download - after that you can remove the oldest patch, so in total it's always not more than x2 space.

**Comment by fasterthanlime** [comment] 2016-10-06 20:02
> It makes sense to download and apply sequence of patches if they are smaller than a full copy

That's what it's supposed to do — it only falls back to a full download if there's been an error applying the patches somehow. Do you remember which game you've been testing with? I would love to reproduce that error since I am working on precisely that this month (in particular, I'm working on applying the patch while it's downloading — and if it fails to apply, to only redownload the corrupted data instead of the full game).

**Comment by quyse** [comment] 2016-10-06 20:10
I just made a test repo and uploaded 8 Mb file, then downloaded it in itch app, closed itch app, added small 10-byte file and uploaded the whole thing as a new version (patch size is like 150 bytes), than added another 10-byte file and uploaded that as well. Then launched itch again, and boom, it's downloading full version (~3 Mb compressed). The repo is `quyse/test1:windows_test` (private). Before that I noticed the same behavior with my FLAW project (because I didn't boot up Windows system for a while), which made me to repro that cleanly :)

**Comment by fasterthanlime** [comment] 2016-10-07 06:16
@quyse could you post both your `itch.txt` and `itch.updater.txt`? (in `~ITCH/logs/` where `~ITCH` is `~/.config/itch` on Linux and `%APPDATA%/itch` on Windows)

**Comment by quyse** [comment] 2016-10-07 12:09
Ok, I got that I was wrong and itch already supports applying multiple patches, sorry :) I tried the same thing on Linux and it worked correctly. On Windows yesterday it actually downloaded two patches, and seems like an error prevented itch from applying them:
`*os.PathError remove C:\Users\Quyse\AppData\Roaming\itch\apps\test 1: The directory is not empty.` (see below for full log). There's no extra files in this directory, and I don't know why it happened. Today I tried the same thing with two patches again on Windows, and it worked.

Yeah, and about the FLAW case, I noticed that it was downloading bigger thing than usual (which leaded me to all this). I looked into logs, and turned out that local version was 6 versions behind current version, so itch downloaded and applied 6 patches in a row successfully. A little problem here is that those 6 patches are >8 Mb in total, so it's more efficient to just download archive (2.6 Mb) (I'm looking at sizes of files in `downloads` directory).

Relevant parts of the logs (for "test1" case):

`itch.txt`:

```
[2016-10-06 @ 22:36:16.249] [reactors/tasks] Should download 213873, has dl key ? false
[2016-10-06 @ 22:36:16.353] [download-watcher] 9440085e-95e3-4d84-aab1-954e10355500 is the new active download
[2016-10-06 @ 22:36:16.353] [download-watcher] Starting download...
[2016-10-06 @ 22:36:16.354] [download] Got an upgrade path, downloading patches
[2016-10-06 @ 22:36:16.354] [download-patches] Dealing with entry {
  "version": 4,
  "patchSize": 152,
  "id": 7557
}
[2016-10-06 @ 22:36:16.354] [download-patches] Downloading build 7557's patch to C:\Users\Quyse\AppData\Roaming\itch\downloads\213873-7557.pwr
[2016-10-06 @ 22:36:16.354] [download-patches] byteOffset = 0, entry.patchSize = 152
[2016-10-06 @ 22:36:16.615] [download] commondatastorage.googleapis.com -> C:\Users\Quyse\AppData\Roaming\itch\downloads\213873-7557.pwr
[2016-10-06 @ 22:36:16.615] [download] starting download!
[2016-10-06 @ 22:36:16.617] [download] commondatastorage.googleapis.com -> C:\Users\Quyse\AppData\Roaming\itch\downloads\213873-7557.pwr.sig
[2016-10-06 @ 22:36:16.617] [download] starting download!
[2016-10-06 @ 22:36:16.617] [download] butler download
[2016-10-06 @ 22:36:16.618] [download] butler download
[2016-10-06 @ 22:36:17.017] [butler] butler: Downloading 3.0 KiB from UploadServer at commondatastorage.googleapis.com
[2016-10-06 @ 22:36:17.022] [download] finished
[2016-10-06 @ 22:36:17.441] [butler] butler: Downloading 152 B from UploadServer at commondatastorage.googleapis.com
[2016-10-06 @ 22:36:17.448] [download] finished
[2016-10-06 @ 22:36:17.448] [download-patches] downloaded both patch + signature
[2016-10-06 @ 22:36:17.449] [download-patches] Dealing with entry {
  "version": 5,
  "patchSize": 162,
  "id": 7558
}
[2016-10-06 @ 22:36:17.450] [download-patches] patch entry: {
  "version": 4,
  "patchSize": 152,
  "id": 7557
}
[2016-10-06 @ 22:36:17.450] [download-patches] Applying 7557 into C:\Users\Quyse\AppData\Roaming\itch\apps\test 1
[2016-10-06 @ 22:36:17.454] [download-patches] Downloading build 7558's patch to C:\Users\Quyse\AppData\Roaming\itch\downloads\213873-7558.pwr
[2016-10-06 @ 22:36:17.454] [download-patches] byteOffset = 152, entry.patchSize = 162
[2016-10-06 @ 22:36:17.498] [butler] butler: âˆ™ Patching C:\Users\Quyse\AppData\Roaming\itch\apps\test 1 with validation
[2016-10-06 @ 22:36:17.511] [download-watcher] Download threw
[2016-10-06 @ 22:36:17.511] [download-watcher] Download ended, err: *os.PathError remove C:\Users\Quyse\AppData\Roaming\itch\apps\test 1: The directory is not empty.
C:/Multi-Runner/builds/58469115/0/itchio/butler/src/github.com/itchio/butler/vendor/github.com/itchio/wharf/pwr/apply.go:161 (0x581a1e)
C:/Multi-Runner/builds/58469115/0/itchio/butler/src/github.com/itchio/butler/wharf_ops.go:281 (0x413611)
C:/Multi-Runner/builds/58469115/0/itchio/butler/src/github.com/itchio/butler/wharf_ops.go:228 (0x413032)
C:/Multi-Runner/builds/58469115/0/itchio/butler/src/github.com/itchio/butler/main.go:400 (0x416ad3)
C:/Go/src/runtime/proc.go:183 (0x4490de)
C:/Go/src/runtime/asm_386.s:1612 (0x472e81)

[2016-10-06 @ 22:36:17.512] [reactors/tasks] Incremental didn't work, doing full download
[2016-10-06 @ 22:36:17.513] [reactors/tasks] Should download 213873, has dl key ? false
[2016-10-06 @ 22:36:17.519] [download-watcher] Download done!
[2016-10-06 @ 22:36:17.609] [download-watcher] 364cd733-a768-46b7-8c57-ac65d1ba4731 is the new active download
[2016-10-06 @ 22:36:17.609] [download-watcher] Starting download...
[2016-10-06 @ 22:36:17.684] [download] commondatastorage.googleapis.com -> C:\Users\Quyse\AppData\Roaming\itch\downloads\213873-7558.pwr
[2016-10-06 @ 22:36:17.684] [download] starting download!
[2016-10-06 @ 22:36:17.684] [download] commondatastorage.googleapis.com -> C:\Users\Quyse\AppData\Roaming\itch\downloads\213873-7558.pwr.sig
[2016-10-06 @ 22:36:17.685] [download] starting download!
[2016-10-06 @ 22:36:17.685] [download] butler download
[2016-10-06 @ 22:36:17.685] [download] butler download
[2016-10-06 @ 22:36:17.888] [download] commondatastorage.googleapis.com -> C:\Users\Quyse\AppData\Roaming\itch\downloads\213873-7558.zip
[2016-10-06 @ 22:36:17.888] [download] starting download!
[2016-10-06 @ 22:36:17.888] [download] butler download
[2016-10-06 @ 22:36:18.197] [butler] butler: Downloading 162 B from UploadServer at commondatastorage.googleapis.com
[2016-10-06 @ 22:36:18.201] [download] finished
[2016-10-06 @ 22:36:18.215] [butler] butler: Downloading 3.1 KiB from UploadServer at commondatastorage.googleapis.com
[2016-10-06 @ 22:36:18.221] [download] finished
[2016-10-06 @ 22:36:18.221] [download-patches] downloaded both patch + signature
[2016-10-06 @ 22:36:18.859] [butler] butler: Downloading 2.3 MiB from UploadServer at commondatastorage.googleapis.com
[2016-10-06 @ 22:36:28.378] [download-watcher] Cancelling/clearing out last download
[2016-10-06 @ 22:36:28.387] [download] couldn't finish download: cancelled
[2016-10-06 @ 22:36:28.387] [download-watcher] Download threw
[2016-10-06 @ 22:36:28.387] [download-watcher] Download cancelled
[2016-10-06 @ 22:36:32.826] [reactors/tasks] Should download 213873, has dl key ? false
[2016-10-06 @ 22:36:32.968] [download-watcher] cdfc5fba-b0c3-446d-810b-c8f1643a5976 is the new active download
[2016-10-06 @ 22:36:32.968] [download-watcher] Starting download...
[2016-10-06 @ 22:36:32.968] [download] Got an upgrade path, downloading patches
[2016-10-06 @ 22:36:32.968] [download-patches] Dealing with entry {
  "version": 4,
  "patchSize": 152,
  "id": 7557
}
[2016-10-06 @ 22:36:32.968] [download-patches] Downloading build 7557's patch to C:\Users\Quyse\AppData\Roaming\itch\downloads\213873-7557.pwr
[2016-10-06 @ 22:36:32.968] [download-patches] byteOffset = 0, entry.patchSize = 152
[2016-10-06 @ 22:36:33.163] [download] commondatastorage.googleapis.com -> C:\Users\Quyse\AppData\Roaming\itch\downloads\213873-7557.pwr
[2016-10-06 @ 22:36:33.163] [download] starting download!
[2016-10-06 @ 22:36:33.163] [download] commondatastorage.googleapis.com -> C:\Users\Quyse\AppData\Roaming\itch\downloads\213873-7557.pwr.sig
[2016-10-06 @ 22:36:33.163] [download] starting download!
[2016-10-06 @ 22:36:33.163] [download] butler download
[2016-10-06 @ 22:36:33.163] [download] butler download
[2016-10-06 @ 22:36:33.886] [butler] butler: Already fully downloaded
[2016-10-06 @ 22:36:33.889] [download] finished
[2016-10-06 @ 22:36:33.890] [butler] butler: Already fully downloaded
[2016-10-06 @ 22:36:33.891] [download] finished
[2016-10-06 @ 22:36:33.891] [download-patches] downloaded both patch + signature
[2016-10-06 @ 22:36:33.891] [download-patches] Dealing with entry {
  "version": 5,
  "patchSize": 162,
  "id": 7558
}
[2016-10-06 @ 22:36:33.891] [download-patches] patch entry: {
  "version": 4,
  "patchSize": 152,
  "id": 7557
}
[2016-10-06 @ 22:36:33.891] [download-patches] Applying 7557 into C:\Users\Quyse\AppData\Roaming\itch\apps\test 1
[2016-10-06 @ 22:36:33.891] [download-patches] Downloading build 7558's patch to C:\Users\Quyse\AppData\Roaming\itch\downloads\213873-7558.pwr
[2016-10-06 @ 22:36:33.891] [download-patches] byteOffset = 152, entry.patchSize = 162
[2016-10-06 @ 22:36:33.940] [butler] butler: âˆ™ Patching C:\Users\Quyse\AppData\Roaming\itch\apps\test 1 with validation
[2016-10-06 @ 22:36:33.950] [download-watcher] Download threw
[2016-10-06 @ 22:36:33.950] [download-watcher] Download ended, err: *os.PathError remove C:\Users\Quyse\AppData\Roaming\itch\apps\test 1: The directory is not empty.
C:/Multi-Runner/builds/58469115/0/itchio/butler/src/github.com/itchio/butler/vendor/github.com/itchio/wharf/pwr/apply.go:161 (0x581a1e)
C:/Multi-Runner/builds/58469115/0/itchio/butler/src/github.com/itchio/butler/wharf_ops.go:281 (0x413611)
C:/Multi-Runner/builds/58469115/0/itchio/butler/src/github.com/itchio/butler/wharf_ops.go:228 (0x413032)
C:/Multi-Runner/builds/58469115/0/itchio/butler/src/github.com/itchio/butler/main.go:400 (0x416ad3)
C:/Go/src/runtime/proc.go:183 (0x4490de)
C:/Go/src/runtime/asm_386.s:1612 (0x472e81)

[2016-10-06 @ 22:36:33.951] [reactors/tasks] Incremental didn't work, doing full download
[2016-10-06 @ 22:36:33.951] [reactors/tasks] Should download 213873, has dl key ? false
[2016-10-06 @ 22:36:33.956] [download-watcher] Download done!
[2016-10-06 @ 22:36:33.972] [download-watcher] 2cc5c8df-1580-48d0-bf30-961657cdb3fd is the new active download
[2016-10-06 @ 22:36:33.972] [download-watcher] Starting download...
[2016-10-06 @ 22:36:34.095] [download] commondatastorage.googleapis.com -> C:\Users\Quyse\AppData\Roaming\itch\downloads\213873-7558.pwr
[2016-10-06 @ 22:36:34.095] [download] starting download!
[2016-10-06 @ 22:36:34.095] [download] commondatastorage.googleapis.com -> C:\Users\Quyse\AppData\Roaming\itch\downloads\213873-7558.pwr.sig
[2016-10-06 @ 22:36:34.095] [download] starting download!
[2016-10-06 @ 22:36:34.111] [download] butler download
[2016-10-06 @ 22:36:34.111] [download] butler download
[2016-10-06 @ 22:36:34.317] [download] commondatastorage.googleapis.com -> C:\Users\Quyse\AppData\Roaming\itch\downloads\213873-7558.zip
[2016-10-06 @ 22:36:34.317] [download] starting download!
[2016-10-06 @ 22:36:34.317] [download] butler download
[2016-10-06 @ 22:36:34.818] [butler] butler: Already fully downloaded
[2016-10-06 @ 22:36:34.821] [download] finished
[2016-10-06 @ 22:36:34.821] [butler] butler: Already fully downloaded
[2016-10-06 @ 22:36:34.824] [download] finished
[2016-10-06 @ 22:36:34.824] [download-patches] downloaded both patch + signature
[2016-10-06 @ 22:36:34.868] [butler] butler: Resuming (1.3 MiB + 1.0 MiB = 2.3 MiB) download from UploadServer at commondatastorage.googleapis.com
[2016-10-06 @ 22:36:37.920] [download] finished
[2016-10-06 @ 22:36:37.920] [download-watcher] Download ended, err: <none>
[2016-10-06 @ 22:36:37.921] [reactors/tasks] Download finished, installing..
[2016-10-06 @ 22:36:37.923] [reactors/tasks] About to start install (304830be-baa9-4efa-8f5b-8a1906edb5af)
[2016-10-06 @ 22:36:37.934] [reactors/tasks] Starting install (304830be-baa9-4efa-8f5b-8a1906edb5af)...
[2016-10-06 @ 22:36:37.935] [tasks/install] upgrading from build id 1958 => build id 7558
[2016-10-06 @ 22:36:37.939] [download-watcher] Download done!
[2016-10-06 @ 22:36:37.940] [tasks/install] comparing mtimes, installed = 1475782326776, archive = Thu Oct 06 2016 22:36:37 GMT+0300 (Russia TZ 2 Standard Time)
[2016-10-06 @ 22:36:37.943] [install/core] retrieving installer type of C:\Users\Quyse\AppData\Roaming\itch\downloads\213873-7558.zip from cache
[2016-10-06 @ 22:36:37.943] [install/core] using cached installer type archive for C:\Users\Quyse\AppData\Roaming\itch\downloads\213873-7558.zip
[2016-10-06 @ 22:36:37.978] [download-watcher] Cancelling/clearing out last download
[2016-10-06 @ 22:36:38.043] [installers/archive] extracting archive 'C:\Users\Quyse\AppData\Roaming\itch\downloads\213873-7558.zip' to 'C:\Users\Quyse\AppData\Roaming\itch\downloads\213873-7558.zip-stage'
[2016-10-06 @ 22:36:38.093] [util/extract] Using butler to extract zip
[2016-10-06 @ 22:36:38.138] [butler] butler: Extracting a zip archive to C:\Users\Quyse\AppData\Roaming\itch\downloads\213873-7558.zip-stage
[2016-10-06 @ 22:36:38.909] [butler] butler: Extracted 0 dirs, 3 files, 0 symlinks
[2016-10-06 @ 22:36:38.909] [installers/archive] extracted all files C:\Users\Quyse\AppData\Roaming\itch\downloads\213873-7558.zip into staging area
[2016-10-06 @ 22:36:38.959] [deploy] cleaning up dest path C:\Users\Quyse\AppData\Roaming\itch\apps\test 1
[2016-10-06 @ 22:36:38.959] [deploy] Could not read receipt: ENOENT: no such file or directory, open 'C:\Users\Quyse\AppData\Roaming\itch\apps\test 1\.itch\receipt.json'
[2016-10-06 @ 22:36:38.959] [deploy] Globbing for destfiles
[2016-10-06 @ 22:36:38.959] [deploy] dest has 2 potential dinosaurs
[2016-10-06 @ 22:36:38.959] [deploy] no dinosaurs
[2016-10-06 @ 22:36:38.959] [deploy] merging stage with dest
[2016-10-06 @ 22:36:39.708] [deploy] everything copied, writing receipt
[2016-10-06 @ 22:36:39.712] [installers/archive] wiping stage...
[2016-10-06 @ 22:36:39.760] [installers/archive] done wiping stage
[2016-10-06 @ 22:36:39.760] [reactors/tasks] Checking results for install (304830be-baa9-4efa-8f5b-8a1906edb5af)...
```

`itch.updater.txt`:

```
[2016-10-06 @ 22:36:32.624] [updater] Looking for new builds of test 1, from build 1958 (upload 213873)
[2016-10-06 @ 22:36:32.624] [updater] Got new build available: 7558 > 1958
[2016-10-06 @ 22:36:32.825] [updater] Got 2 patches to download, 314 bytes total
[2016-10-06 @ 22:36:32.831] [updater] Done looking for updates for cave 9138e0d6-502b-4e13-b598-998b0c0c0610
```

**Comment by fasterthanlime** [comment] 2016-10-07 12:54
> A little problem here is that those 6 patches are >8 Mb in total, so it's more efficient to just download archive (2.6 Mb) (I'm looking at sizes of files in downloads directory).

Indeed! That particular optimization isn't in the app yet.

---

According to the logs, butler failed to delete `deleted files`, the relevant code is [right there](https://github.com/itchio/butler/blob/1a83db15fdfa208622b8b3564a4002836d38a4dc/vendor/github.com/itchio/wharf/pwr/apply.go#L373).

## Theory

I think that error could happen in a scenario like that:
- An app ships with files `app.exe` and `data1/template`
- Running the app creates file in `data1/` such as `data1/user1`, `data1/user2`
- An update ships, with `app.exe` and `data2/template` (but not `data1/`)

butler detects that `data1` was removed and tries to delete the folder (after deleting `data1/template`) but `data1/user1` and `data1/user2` are still there, so it fails.

I think that error can be safely ignored (and leave behind user-generated files), I'll write a test case for that right now.

**Comment by fasterthanlime** [comment] 2016-10-07 12:55
Closing in favor of https://github.com/itchio/butler/issues/63

**Closed as completed by fasterthanlime** 2016-10-07 12:55 UTC
Labels: bug
