### ISSUE TITLE
[win32] Issue for v0.13.2

### ISSUE THREAD

**Issue by MBoffin** [itchio/itch#463] opened 2016-02-22 06:42 UTC
For several versions now, I can never get Kenney Game Assets to actually finish installing. (His v1 pack, not v2.) It does the download, says it's installing, then never actually _finishes_ installing. If I quit the app, when I re-open it, it immediately tried re-downloading and installing again. This happens on other computers too. Not just this one. I did purchase it twice at different times, so on the itch.io web site it says I own it twice, so maybe that has something to do with it?

Kenney Game Assets 2 works fine and installs without a hitch. But the attached screenshot is where the first pack sits.

![installing](https://cloud.githubusercontent.com/assets/673691/13211314/2c55fb8a-d8ec-11e5-8586-90c609ec018b.png)

**Comment by fasterthanlime** [comment] 2016-02-22 14:59
duplicate of #455, I'm taking a look at this family of issues today

**Closed as completed by fasterthanlime** 2016-02-22 14:59 UTC
