### ISSUE TITLE
Update breaks game on linux until reinstalled

### ISSUE THREAD

**Issue by slowriot** [itchio/itch#660] opened 2016-05-25 21:23 UTC
After our game AdvertCity is updated through butler, it fails to launch:
![](https://i.imgur.com/iiI1131.png)

When itch is run from the console, the following occurs when trying to execute:

```
[2016-05-25 @ 22:11:42] [sagas/tasks] Have a cave for game 4287, launching
[2016-05-25 @ 22:11:42] [sagas/tasks] Starting cave e9660060-0721-488a-923c-47829a695c58: stub
[2016-05-25 @ 22:11:42] [sagas/tasks] About to start launch (6625eb07-89ce-441b-8263-5aed15db13cf)
[2016-05-25 @ 22:11:42] [sagas/tasks] Starting launch (6625eb07-89ce-441b-8263-5aed15db13cf)...
[2016-05-25 @ 22:11:42] [tasks/launch] initial candidate set: [
  {
    "path": "182368"
  },
  {
    "path": "AdvertCity"
  }
]
[2016-05-25 @ 22:11:42] [tasks/launch] candidates after weight sorting: [
  {
    "path": "AdvertCity",
    "weight": 151652488,
    "score": 100,
    "depth": 1
  },
  {
    "path": "182368",
    "weight": 151331952,
    "score": 100,
    "depth": 1
  }
]
[2016-05-25 @ 22:11:42] [tasks/launch] candidates after score sorting: [
  {
    "path": "AdvertCity",
    "weight": 151652488,
    "score": 100,
    "depth": 1
  },
  {
    "path": "182368",
    "weight": 151331952,
    "score": 100,
    "depth": 1
  }
]
[2016-05-25 @ 22:11:42] [tasks/launch] candidates after depth sorting: [
  {
    "path": "AdvertCity",
    "weight": 151652488,
    "score": 100,
    "depth": 1
  },
  {
    "path": "182368",
    "weight": 151331952,
    "score": 100,
    "depth": 1
  }
]
[2016-05-25 @ 22:11:42] [tasks/launch] launching '/home/slowriot/.config/itch/apps/AdvertCity/AdvertCity' on 'linux' with args ''
[2016-05-25 @ 22:11:42] [tasks/launch] sh "/home/slowriot/.config/itch/apps/AdvertCity/AdvertCity"
[2016-05-25 @ 22:11:42] [tasks/launch] Working directory: /home/slowriot/.config/itch/apps/AdvertCity
[2016-05-25 @ 22:11:42] [sagas/tasks] Task threw
[2016-05-25 @ 22:11:42] [sagas/tasks] Task ended, err: Error: spawn EACCES
    at exports._errnoException (util.js:890:11)
    at ChildProcess.spawn (internal/child_process.js:302:11)
    at Object.exports.spawn (child_process.js:379:9)
    at spawn (/usr/lib/itch/resources/app.asar/appsrc/util/spawn.js:31:28)
    at /usr/lib/itch/resources/app.asar/appsrc/tasks/launch/native.js:28:22
    at undefined.next (native)
From previous event:
    at sh (/usr/lib/itch/resources/app.asar/app/tasks/launch/native.js:40:16)
    at launchExecutable (/usr/lib/itch/resources/app.asar/appsrc/tasks/launch/native.js:138:12)
    at /usr/lib/itch/resources/app.asar/appsrc/tasks/launch/native.js:186:10
    at undefined.next (native)
    at tryOnImmediate (timers.js:534:15)
    at processImmediate [as _immediateCallback] (timers.js:514:5)
From previous event:
    at launch (/usr/lib/itch/resources/app.asar/app/tasks/launch/native.js:254:16)
    at /usr/lib/itch/resources/app.asar/appsrc/tasks/launch.js:73:11
    at undefined.next (native)
    at start (/usr/lib/itch/resources/app.asar/app/tasks/launch.js:112:16)
    at runCallEffect (/usr/lib/itch/resources/app.asar/node_modules/redux-saga/lib/internal/proc.js:445:19)
    at runEffect (/usr/lib/itch/resources/app.asar/node_modules/redux-saga/lib/internal/proc.js:375:399)
    at /usr/lib/itch/resources/app.asar/node_modules/redux-saga/lib/internal/proc.js:640:14
    at Array.forEach (native)
    at runRaceEffect (/usr/lib/itch/resources/app.asar/node_modules/redux-saga/lib/internal/proc.js:639:10)
    at runEffect (/usr/lib/itch/resources/app.asar/node_modules/redux-saga/lib/internal/proc.js:375:304)
    at next (/usr/lib/itch/resources/app.asar/node_modules/redux-saga/lib/internal/proc.js:259:9)
    at currCb (/usr/lib/itch/resources/app.asar/node_modules/redux-saga/lib/internal/proc.js:329:7)
    at runSelectEffect (/usr/lib/itch/resources/app.asar/node_modules/redux-saga/lib/internal/proc.js:650:7)
    at runEffect (/usr/lib/itch/resources/app.asar/node_modules/redux-saga/lib/internal/proc.js:375:848)
From previous event:
    at start (/usr/lib/itch/resources/app.asar/app/tasks/launch.js:112:16)
    at runCallEffect (/usr/lib/itch/resources/app.asar/node_modules/redux-saga/lib/internal/proc.js:445:19)
    at runEffect (/usr/lib/itch/resources/app.asar/node_modules/redux-saga/lib/internal/proc.js:375:399)
    at /usr/lib/itch/resources/app.asar/node_modules/redux-saga/lib/internal/proc.js:640:14
    at Array.forEach (native)
    at runRaceEffect (/usr/lib/itch/resources/app.asar/node_modules/redux-saga/lib/internal/proc.js:639:10)
    at runEffect (/usr/lib/itch/resources/app.asar/node_modules/redux-saga/lib/internal/proc.js:375:304)
    at next (/usr/lib/itch/resources/app.asar/node_modules/redux-saga/lib/internal/proc.js:259:9)
    at currCb (/usr/lib/itch/resources/app.asar/node_modules/redux-saga/lib/internal/proc.js:329:7)
    at runSelectEffect (/usr/lib/itch/resources/app.asar/node_modules/redux-saga/lib/internal/proc.js:650:7)
    at runEffect (/usr/lib/itch/resources/app.asar/node_modules/redux-saga/lib/internal/proc.js:375:848)
    at next (/usr/lib/itch/resources/app.asar/node_modules/redux-saga/lib/internal/proc.js:259:9)
    at currCb (/usr/lib/itch/resources/app.asar/node_modules/redux-saga/lib/internal/proc.js:329:7)
    at /usr/lib/itch/resources/app.asar/node_modules/redux-saga/lib/internal/proc.js:431:16
    at Function.asap.flush (/usr/lib/itch/resources/app.asar/node_modules/redux-saga/lib/internal/asap.js:26:5)
    at runForkEffect (/usr/lib/itch/resources/app.asar/node_modules/redux-saga/lib/internal/proc.js:531:20)
    at runEffect (/usr/lib/itch/resources/app.asar/node_modules/redux-saga/lib/internal/proc.js:375:577)
    at next (/usr/lib/itch/resources/app.asar/node_modules/redux-saga/lib/internal/proc.js:259:9)
    at currCb (/usr/lib/itch/resources/app.asar/node_modules/redux-saga/lib/internal/proc.js:329:7)
[2016-05-25 @ 22:11:42] [sagas/tasks] Error in task launch: Error: spawn EACCES
```

This does not appear to be a duplicate of #655 - the executable in ~/.config/itch/apps/whatever has correct permissions, and can be called manually - however, it remains the previous version, prior to the update.

**Comment by fasterthanlime** [comment] 2016-05-26 08:49
@slowriot EACCES lets me think the user that's launching the itch app doesn't have read or exec access to the file.. What does `ls -lhA /home/slowriot/.config/itch/apps/AdvertCity/AdvertCity` print ?

**Comment by slowriot** [comment] 2016-05-27 15:15
I'm afraid I'm unable to check that, because I can't reproduce this currently - I reinstalled the game to resolve it, and we haven't had another update since.  I'll let you know if it recurs with our next update, and show you the full stats of the file(s).

**Comment by fasterthanlime** [comment] 2016-05-29 14:44
Alright, please reopen if it happens again! I'm betting on it actually being a duplicate of #655.

**Closed as completed by fasterthanlime** 2016-05-29 14:44 UTC
