### ISSUE TITLE
🏁 Feedback v21.0.4

### ISSUE THREAD

**Issue by dmbsk** [itchio/itch#1079] opened 2016-12-20 18:11 UTC
Event log:

```
Error: ENOSPC: no space left on device, write
    at Error (native)
From previous event:
    at Object.<anonymous> (C:\Users\towek\AppData\Local\itch\app-21.0.4\resources\app.asar\appsrc\util\sf.ts:144:21)
    at next (<anonymous>)
    at fulfilled (C:\Users\towek\AppData\Local\itch\app-21.0.4\resources\app.asar\app\util\sf.js:4:58)
```

**Comment by fasterthanlime** [comment] 2016-12-20 18:11
Your disk is full :)

The app should handle it better - but that's the source of your problem.

**Comment by fasterthanlime** [comment] 2017-04-19 08:29
Duplicate of #874 / #801

**Closed as completed** 2018-09-18 13:50 UTC
