### ISSUE TITLE
[linux] game Tanks of Freedom broken for v0.13.2

### ISSUE THREAD

**Issue by kosciak9** [itchio/itch#533] opened 2016-03-26 22:37 UTC
:rotating_light: game [Tanks of Freedom](https://w84death.itch.io/tanks-of-freedom) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/63d95dfa8aa4f8ed5873).

:running: Any additional details can go here!

**Comment by fasterthanlime** [comment] 2016-05-06 20:29
duplicate of #445

**Closed as completed by fasterthanlime** 2016-05-06 20:29 UTC
