### ISSUE TITLE
Itch app launch issue on latest Ubuntu 18.04

### ISSUE THREAD

**Issue by tomcashman** [itchio/itch#2132] opened 2018-09-18 19:18 UTC
Itch app didn't launch at all on Ubuntu 18.04. When I tried command line I got this error:

`./itch: error while loading shared libraries: libgconf-2.so.4: cannot open shared object file: No such file or directory
`

Resolved with
`sudo apt-get install libgconf-2-4`

**Comment by fasterthanlime** [comment] 2018-09-19 11:11
Duplicate of https://github.com/itchio/itch/issues/2121

**Closed as completed by fasterthanlime** 2018-09-19 11:11 UTC
Labels: bug, linux, v25.x
