### ISSUE TITLE
[win32] Crash report for v0.10.2 - Opening app twice causes crash.

### ISSUE THREAD

**Issue by travisfoo** [itchio/itch#173] opened 2015-12-17 23:34 UTC
How to replicate:

1) Start itch.
2) Start itch again.

I came across this while trying to pin itch to the taskbar.

Crash log:

```
Error: Cannot find module '../protocol'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.defineProperties.protocol.get [as protocol] (C:\Users\Travis Fort\AppData\Local\itch\app-0.10.2\resources\atom.asar\browser\api\lib\exports\electron.js:75:16)
    at EventEmitter.<anonymous> (C:\Users\Travis Fort\AppData\Local\itch\app-0.10.2\resources\atom.asar\browser\lib\chrome-extension.js:75:24)
    at EventEmitter.g (events.js:260:16)
    at emitOne (events.js:82:20)
    at EventEmitter.emit (events.js:169:7)
```

**Comment by fasterthanlime** [comment] 2015-12-19 18:20
duplicate of #202

**Closed as completed by fasterthanlime** 2015-12-19 18:20 UTC
