### ISSUE TITLE
[win 32]Front End Showing Removed Games

### ISSUE THREAD

**Issue by titch71** [itchio/itch#429] opened 2016-01-29 00:16 UTC
Front end shows my collection games that have been removed from itch.io.

Games no longer show on the website so cannot delete them

no more bullets is an example

**Comment by fasterthanlime** [comment] 2016-01-29 10:21
Duplicate of #262 — it's just cached locally, no worries :) Will be fixed in a later version.

**Closed as completed by fasterthanlime** 2016-01-29 10:21 UTC
