### ISSUE TITLE
[win32] Crash report for v0.10.2

### ISSUE THREAD

**Issue by hashalon** [itchio/itch#201] opened 2015-12-19 17:20 UTC
Looks like the auto updater is not working properly.
Crash log:

```
Error: Cannot find module '../protocol'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.defineProperties.protocol.get [as protocol] (C:\Users\olivi\AppData\Local\itch\app-0.10.2\resources\atom.asar\browser\api\lib\exports\electron.js:75:16)
    at EventEmitter.<anonymous> (C:\Users\olivi\AppData\Local\itch\app-0.10.2\resources\atom.asar\browser\lib\chrome-extension.js:75:24)
    at EventEmitter.g (events.js:260:16)
    at emitOne (events.js:82:20)
    at EventEmitter.emit (events.js:169:7)
```

**Comment by fasterthanlime** [comment] 2015-12-19 17:45
@harraps do you remember which version you were upgrading from?

itch actually stays alive in your tray until you actually quit it with Ctrl-Q, File -> Exit, or Right click -> Exit on the tray icon — when launching it a second time, it should bring up (focus) the existing instance and immediately quit. That seems to be when this error happens.

As to why it happens during the auto update process, if you're upgrading from before 0.9.4, it's a known issue. Otherwise, I'll have to look some more into it.

**Comment by fasterthanlime** [comment] 2015-12-19 18:20
duplicate of #202

**Closed as completed by fasterthanlime** 2015-12-19 18:20 UTC
