### ISSUE TITLE
🏁 Feedback v22.2.0

### ISSUE THREAD

**Issue by truhlikfredy** [itchio/itch#1094] opened 2016-12-29 19:07 UTC
Application crashes when you run out of the free HDD space

Event log:

```
Error: ENOSPC: no space left on device, open 'C:\Users\Fredy\AppData\Roaming\itch\users\385293\marketdb\collections\123757.tmp72'
    at Error (native)
From previous event:
    at Object.<anonymous> (C:\Users\Fredy\AppData\Local\itch\app-22.2.0\resources\app.asar\appsrc\util\sf.ts:146:21)
    at next (<anonymous>)
    at fulfilled (C:\Users\Fredy\AppData\Local\itch\app-22.2.0\resources\app.asar\app\util\sf.js:12:58)
```

**Comment by fasterthanlime** [comment] 2017-04-19 08:28
Duplicate of #874 / #801

**Closed as completed by fasterthanlime** 2017-04-19 08:28 UTC
