### ISSUE TITLE
🏁 Feedback v23.4.2

### ISSUE THREAD

**Issue by ghost** [itchio/itch#1492] opened 2017-09-01 23:09 UTC
Event log:

```
Error: ENOSPC: no space left on device, write
```

**Comment by fasterthanlime** [comment] 2017-09-02 01:07
Your disk is full! Make some room :)

Another issue tracks the app handling that in a more user-friendly way rather than just throwing "ENOSPC" at you, marking this as a duplicate of #874

**Closed as completed by fasterthanlime** 2017-09-02 01:07 UTC
