### ISSUE TITLE
Wine and Linux

### ISSUE THREAD

**Issue by ca5ua1** [itchio/itch#2359] opened 2020-01-28 14:53 UTC
What about execute Win games in Linux trow Wine. Because it isn't handy to install itch inside Wine. (You can silently steal Wine config how it is in Lutris (for advanced users), I will keep my mounth shut, nobody will notice)

**Comment by fasterthanlime** [comment] 2020-01-28 17:42
Duplicate of #433

**Closed as completed by fasterthanlime** 2020-01-28 17:42 UTC
