### ISSUE TITLE
404 of Restricted content for Creator

### ISSUE THREAD

**Issue by josefnpat** [itchio/itch#691] opened 2016-06-10 16:36 UTC
I am using `itch` version `0.14.0` on Arch Linux.

This is obviously low priority, but I have a game set to "Restricted — Only authorized people can view the page".

Unfortunately I cannot see the page, even though I am the creator.

![image](https://cloud.githubusercontent.com/assets/646162/15971523/1633337c-2eff-11e6-9a00-8e1fc3c5a259.png)

**Comment by fasterthanlime** [comment] 2016-06-10 17:37
Hey @josefnpat, that's a duplicate of #672 - app login and website login are currently separate, as they don't offer the same level of access. See also #670 which needs to be addressed first for #672 to be implemented.

All you need to do is click the address bar, type `itch.io/login`, hit Enter, and then you'll be logged into the website (simply navigate 'back' to the game page, or just close/reopen it). This login will persist across restarts of the app.

**Closed as completed** 2016-06-10 19:54 UTC
